import type { CaptionTrack } from './types';

export const CAPTION_PREF_STORAGE_KEY = 'captionPreferenceByHost';

const MAX_HOSTS = 80;

export type CaptionLanguagePreference = {
  enabled: boolean;
  language: string;
  autoGenerated: boolean;
};

export function captionPreferenceHost(hostname = ''): string {
  const host = hostname.replace(/^www\./i, '').toLowerCase();
  if (!host) return '';
  if (host === 'youtu.be' || host === 'youtube-nocookie.com' || host.endsWith('.youtube.com')) {
    return 'youtube.com';
  }
  if (host === 'vimeo.com' || host.endsWith('.vimeo.com')) return 'vimeo.com';
  return host;
}

export function normalizeLanguageCode(code: string): string {
  return code.trim().toLowerCase().replace(/_/g, '-');
}

export function languagesCompatible(left: string, right: string): boolean {
  const a = normalizeLanguageCode(left);
  const b = normalizeLanguageCode(right);
  if (!a || !b) return false;
  if (a === b) return true;
  return a.split('-')[0] === b.split('-')[0];
}

export function resolveCaptionLanguagePreference(value: unknown): CaptionLanguagePreference | null {
  if (!value || typeof value !== 'object') return null;
  const raw = value as Record<string, unknown>;
  const language = typeof raw.language === 'string' ? normalizeLanguageCode(raw.language) : '';
  if (!language) {
    return raw.enabled === true ? null : { enabled: false, language: '', autoGenerated: false };
  }
  return {
    enabled: raw.enabled !== false,
    language,
    autoGenerated: raw.autoGenerated === true
  };
}

export function resolveCaptionPreferenceMap(value: unknown): Record<string, CaptionLanguagePreference> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
  const map: Record<string, CaptionLanguagePreference> = {};
  for (const [host, item] of Object.entries(value as Record<string, unknown>)) {
    const key = captionPreferenceHost(host);
    const pref = resolveCaptionLanguagePreference(item);
    if (!key || !pref) continue;
    map[key] = pref;
  }
  return map;
}

export function upsertCaptionPreference(
  map: Record<string, CaptionLanguagePreference>,
  host: string,
  pref: CaptionLanguagePreference
): Record<string, CaptionLanguagePreference> {
  const key = captionPreferenceHost(host);
  if (!key) return map;
  const next: Record<string, CaptionLanguagePreference> = { ...map, [key]: pref };
  const keys = Object.keys(next);
  if (keys.length <= MAX_HOSTS) return next;
  for (const extra of keys) {
    if (extra === key) continue;
    delete next[extra];
    if (Object.keys(next).length <= MAX_HOSTS) break;
  }
  return next;
}

export function findPreferredCaptionTrack(
  tracks: CaptionTrack[],
  pref: { language: string; autoGenerated: boolean } | null
): CaptionTrack | null {
  if (!pref?.language) return null;
  const withLang = tracks.filter((track) => normalizeLanguageCode(track.language));
  const sameKind = withLang.find((track) => (
    languagesCompatible(track.language, pref.language)
    && Boolean(track.autoGenerated) === pref.autoGenerated
  ));
  if (sameKind) return sameKind;
  return withLang.find((track) => languagesCompatible(track.language, pref.language)) || null;
}
