import { allSettledResults, fulfilledValues } from '../core/result';
import type {
  CaptionActivationResult,
  CaptionTrack,
  Chapter,
  MediaCapabilities,
  MediaFeaturesAdapter,
  PreviewFrame,
  PreviewSource,
  TimelineHeatmap
} from './types';

export function preferProviderCaptionTracks(tracks: CaptionTrack[]): CaptionTrack[] {
  const merged: CaptionTrack[] = [];
  const seen = new Set<string>();
  for (const track of tracks) {
    const key = `${track.source}:${track.language}:${track.label}:${track.autoGenerated ? 'auto' : 'manual'}`;
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(track);
  }
  if (merged.some((track) => track.source === 'patreon' || track.source === 'twitch' || track.source === 'disney')) {
    return merged.filter((track) => track.source !== 'native-text-track');
  }
  return merged;
}

export class CompositeMediaAdapter implements MediaFeaturesAdapter {
  private adapters: MediaFeaturesAdapter[];

  constructor(adapters: MediaFeaturesAdapter[]) {
    this.adapters = adapters;
  }

  /** Combines capabilities from adapters that respond successfully, ignoring rejected probes. */
  async probe(): Promise<MediaCapabilities> {
    const results = fulfilledValues(await allSettledResults(this.adapters.map((adapter) => adapter.probe())));
    return {
      captions: results.some((item) => item.captions),
      chapters: results.some((item) => item.chapters),
      previews: results.some((item) => item.previews)
    };
  }

  /**
   * Merges tracks from successful adapters and drops native tracks when Patreon, Twitch, or Disney
   * tracks are present.
   */
  async listCaptionTracks(): Promise<CaptionTrack[]> {
    const lists = fulfilledValues(await allSettledResults(this.adapters.map((adapter) => adapter.listCaptionTracks())));
    return preferProviderCaptionTracks(lists.flat());
  }

  /**
   * Activates adapters that report the requested track and deactivates the others.
   * Passing `null` deactivates every adapter; failures are isolated so another adapter can respond.
   */
  async activateCaptionTrack(id: string | null): Promise<CaptionActivationResult> {
    if (id === null) {
      await allSettledResults(this.adapters.map((adapter) => adapter.activateCaptionTrack(null)));
      return { status: 'off', delivery: 'none', cues: [] };
    }
    let result: CaptionActivationResult = { status: 'failed', delivery: 'none', cues: [] };
    for (const adapter of this.adapters) {
      let tracks: CaptionTrack[] = [];
      try {
        tracks = await adapter.listCaptionTracks();
      } catch {
        continue;
      }
      try {
        if (tracks.some((track) => track.id === id)) {
          result = await adapter.activateCaptionTrack(id);
        } else {
          await adapter.activateCaptionTrack(null);
        }
      } catch {
        // A failing provider must not prevent native or other captions from activating (F-05).
      }
    }
    return result;
  }

  async refreshCaptionCues(id: string, time: number): Promise<CaptionActivationResult | null> {
    for (const adapter of this.adapters) {
      if (!adapter.refreshCaptionCues) continue;
      try {
        const tracks = await adapter.listCaptionTracks();
        if (tracks.some((track) => track.id === id)) return adapter.refreshCaptionCues(id, time);
      } catch {
        // Keep looking; a provider refresh failure must not break the composite adapter.
      }
    }
    return null;
  }

  /** Returns the first nonempty chapter list, continuing past adapters that fail. */
  async getChapters(): Promise<Chapter[]> {
    for (const adapter of this.adapters) {
      if (!adapter.getChapters) continue;
      try {
        const chapters = await adapter.getChapters();
        if (chapters.length > 0) return chapters;
      } catch {
        // Keep looking; one provider's chapter failure is not fatal.
      }
    }
    return [];
  }

  /** Returns the first heatmap with a drawable path or segments. */
  getHeatmap(): TimelineHeatmap | null {
    for (const adapter of this.adapters) {
      if (!adapter.getHeatmap) continue;
      try {
        const heatmap = adapter.getHeatmap();
        if (heatmap?.svgPath || (heatmap?.segments && heatmap.segments.length > 0)) return heatmap;
      } catch {
        // Keep looking; a missing Most Replayed chart is not fatal.
      }
    }
    return null;
  }

  async getPreviewSource(): Promise<PreviewSource> {
    for (const adapter of this.adapters) {
      if (!adapter.getPreviewSource) continue;
      const source = await adapter.getPreviewSource();
      if (source.kind !== 'none') return source;
    }
    return { kind: 'none', reason: 'unsupported' };
  }

  getPreviewFrame(time: number, duration: number): PreviewFrame | null {
    for (const adapter of this.adapters) {
      const frame = adapter.getPreviewFrame?.(time, duration) || null;
      if (frame) return frame;
    }
    return null;
  }

  mediaId(): string | null {
    for (const adapter of this.adapters) {
      const id = adapter.mediaId?.();
      if (id) return id;
    }
    return null;
  }

  /** Reloads every adapter without rejecting when an individual reload fails. */
  async reload(): Promise<void> {
    await allSettledResults(this.adapters.map((adapter) => adapter.reload?.() ?? Promise.resolve()));
  }

  invalidate(): void {
    this.adapters.forEach((adapter) => adapter.invalidate?.());
  }

  dispose(): void {
    this.adapters.forEach((adapter) => adapter.dispose());
  }
}
