import { allSettledResults, fulfilledValues } from '../core/result';
import type {
  CaptionCue,
  CaptionTrack,
  Chapter,
  MediaCapabilities,
  MediaFeaturesAdapter,
  PreviewFrame,
  PreviewSource
} from './types';

export function preferProviderCaptionTracks(tracks: CaptionTrack[]): CaptionTrack[] {
  const merged: CaptionTrack[] = [];
  const seen = new Set<string>();
  for (const track of tracks) {
    const key = `${track.source}:${track.language}:${track.label}:${track.autoGenerated ? 'auto' : 'manual'}`;
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(track);
  }
  if (merged.some((track) => track.source === 'patreon' || track.source === 'twitch' || track.source === 'disney')) {
    return merged.filter((track) => track.source !== 'native-text-track');
  }
  return merged;
}

export class CompositeMediaAdapter implements MediaFeaturesAdapter {
  private adapters: MediaFeaturesAdapter[];

  constructor(adapters: MediaFeaturesAdapter[]) {
    this.adapters = adapters;
  }

  async probe(): Promise<MediaCapabilities> {
    const results = fulfilledValues(await allSettledResults(this.adapters.map((adapter) => adapter.probe())));
    return {
      captions: results.some((item) => item.captions),
      chapters: results.some((item) => item.chapters),
      previews: results.some((item) => item.previews)
    };
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    const lists = fulfilledValues(await allSettledResults(this.adapters.map((adapter) => adapter.listCaptionTracks())));
    return preferProviderCaptionTracks(lists.flat());
  }

  async activateCaptionTrack(id: string | null): Promise<CaptionCue[] | null> {
    if (id === null) {
      await allSettledResults(this.adapters.map((adapter) => adapter.activateCaptionTrack(null)));
      return null;
    }
    let overlayCues: CaptionCue[] | null = null;
    for (const adapter of this.adapters) {
      let tracks: CaptionTrack[] = [];
      try {
        tracks = await adapter.listCaptionTracks();
      } catch {
        continue;
      }
      try {
        if (tracks.some((track) => track.id === id)) {
          overlayCues = await adapter.activateCaptionTrack(id);
        } else {
          await adapter.activateCaptionTrack(null);
        }
      } catch {
        // A failing provider must not prevent native or other captions from activating (F-05).
      }
    }
    return overlayCues;
  }

  async getChapters(): Promise<Chapter[]> {
    for (const adapter of this.adapters) {
      if (!adapter.getChapters) continue;
      try {
        const chapters = await adapter.getChapters();
        if (chapters.length > 0) return chapters;
      } catch {
        // Keep looking; one provider's chapter failure is not fatal.
      }
    }
    return [];
  }

  async getPreviewSource(): Promise<PreviewSource> {
    for (const adapter of this.adapters) {
      if (!adapter.getPreviewSource) continue;
      const source = await adapter.getPreviewSource();
      if (source.kind !== 'none') return source;
    }
    return { kind: 'none', reason: 'unsupported' };
  }

  getPreviewFrame(time: number, duration: number): PreviewFrame | null {
    for (const adapter of this.adapters) {
      const frame = adapter.getPreviewFrame?.(time, duration) || null;
      if (frame) return frame;
    }
    return null;
  }

  mediaId(): string | null {
    for (const adapter of this.adapters) {
      const id = adapter.mediaId?.();
      if (id) return id;
    }
    return null;
  }

  async reload(): Promise<void> {
    await allSettledResults(this.adapters.map((adapter) => adapter.reload?.() ?? Promise.resolve()));
  }

  invalidate(): void {
    this.adapters.forEach((adapter) => adapter.invalidate?.());
  }

  dispose(): void {
    this.adapters.forEach((adapter) => adapter.dispose());
  }
}
