import { normalizeCaptionLabel, normalizeLanguageCode, pickCaptionTrack, type CaptionLanguageChoice, type CaptionLanguagePreference } from './caption-preference';
import { CaptionRenderer } from './caption-renderer';
import { openCaptionOptionsDialog } from './caption-options-dialog';
import { chapterAtTime } from './cue-index';
import type { CaptionStyle } from './caption-style';
import { DEFAULT_CAPTION_STYLE } from './caption-style';
import { defaultMediaProviderFlags, mediaProviderFlagsEqual, type MediaProviderFlags } from './provider-flags';
import { createMediaFeaturesAdapter } from './resolve-adapter';
import { displayMediaTime } from '../playback-window';
import type { CaptionTrack, Chapter, MediaFeaturesAdapter, PreviewFrame } from './types';

export type CaptionToggleResult = 'on' | 'off' | 'none' | 'failed';

export type CaptionHudPayload = {
  result: CaptionToggleResult;
  label?: string;
};

export type CaptionActivateOptions = {
  persist?: boolean;
  hud?: boolean | 'on';
};

export type CaptionOverlayRenderer = Pick<CaptionRenderer, 'setCues' | 'update' | 'setStyle' | 'dispose'>;

export type MediaFeaturesBindings = {
  video: HTMLVideoElement;
  ccBtn: HTMLButtonElement;
  ccMenu: HTMLDivElement;
  scrubberTrack: HTMLElement;
  t: (key: string, substitutions?: string | string[]) => string;
  onCaptionChange?: () => void;
  onCaptionHud?: (payload: CaptionHudPayload) => void;
  onCaptionStyleChange?: (style: CaptionStyle) => void;
  captionPreference?: CaptionLanguagePreference | null;
  onCaptionPreferenceChange?: (pref: CaptionLanguagePreference) => void;
  providerFlags?: MediaProviderFlags;
  decorateCaptionDialog?: (overlay: HTMLElement) => void;
  adapter?: MediaFeaturesAdapter;
  renderer?: CaptionOverlayRenderer;
};

function setOverlayCaptionsClass(on: boolean): void {
  if (typeof document === 'undefined') return;
  document.documentElement.classList.toggle('theater-using-overlay-captions', on);
}

export type TooltipMediaExtras = {
  chapterTitle: string;
  preview: PreviewFrame | null;
};

export class MediaFeaturesController {
  private adapter: MediaFeaturesAdapter;
  private renderer: CaptionOverlayRenderer;
  private video: HTMLVideoElement;
  private ccBtn: HTMLButtonElement;
  private ccMenu: HTMLDivElement;
  private chapterLayer: HTMLDivElement;
  private t: MediaFeaturesBindings['t'];
  private tracks: CaptionTrack[] = [];
  private chapters: Chapter[] = [];
  private activeTrackId: string | null = null;
  private usingOverlayCaptions = false;
  private disposed = false;
  private refreshInFlight = false;
  private refreshQueued = false;
  private mediaId: string | null = null;
  private captionPreference: CaptionLanguageChoice | null = null;
  private lastLanguagePref: CaptionLanguageChoice | null = null;
  private captionStyle: CaptionStyle = { ...DEFAULT_CAPTION_STYLE };
  private onCaptionChange?: () => void;
  private onCaptionHud?: (payload: CaptionHudPayload) => void;
  private onCaptionStyleChange?: (style: CaptionStyle) => void;
  private onCaptionPreferenceChange?: (pref: CaptionLanguagePreference) => void;
  private decorateCaptionDialog?: (overlay: HTMLElement) => void;
  private providerFlags: MediaProviderFlags = defaultMediaProviderFlags();
  private opChain: Promise<void> = Promise.resolve();
  private activateGeneration = 0;
  private activateInFlight = false;

  constructor(bindings: MediaFeaturesBindings) {
    this.providerFlags = bindings.providerFlags || defaultMediaProviderFlags();
    this.adapter = bindings.adapter || createMediaFeaturesAdapter(bindings.video, this.providerFlags);
    this.renderer = bindings.renderer || new CaptionRenderer(bindings.onCaptionChange);
    this.video = bindings.video;
    this.ccBtn = bindings.ccBtn;
    this.ccMenu = bindings.ccMenu;
    this.t = bindings.t;
    this.onCaptionChange = bindings.onCaptionChange;
    this.onCaptionHud = bindings.onCaptionHud;
    this.onCaptionStyleChange = bindings.onCaptionStyleChange;
    this.onCaptionPreferenceChange = bindings.onCaptionPreferenceChange;
    this.decorateCaptionDialog = bindings.decorateCaptionDialog;
    const pref = bindings.captionPreference;
    if (pref && (pref.language || pref.label)) {
      this.lastLanguagePref = {
        language: pref.language,
        autoGenerated: pref.autoGenerated,
        ...(pref.label ? { label: pref.label } : {})
      };
      if (pref.enabled) this.captionPreference = this.lastLanguagePref;
    }
    if (typeof document === 'undefined') {
      this.chapterLayer = {
        className: '',
        replaceChildren() {},
        remove() {},
        appendChild() { return null; }
      } as unknown as HTMLDivElement;
    } else {
      this.chapterLayer = document.createElement('div');
      this.chapterLayer.className = 'theater-scrubber-chapters';
      bindings.scrubberTrack.appendChild(this.chapterLayer);
    }
  }

  async start(): Promise<void> {
    await this.refresh();
  }

  setProviderFlags(flags: MediaProviderFlags): void {
    if (this.disposed || mediaProviderFlagsEqual(this.providerFlags, flags)) return;
    this.providerFlags = flags;
    this.adapter.dispose();
    this.adapter = createMediaFeaturesAdapter(this.video, flags);
    this.invalidate();
    void this.refresh();
  }

  invalidate(): void {
    if (this.disposed) return;
    this.activateGeneration += 1;
    this.adapter.invalidate?.();
    void this.adapter.activateCaptionTrack(null);
    this.tracks = [];
    this.chapters = [];
    this.activeTrackId = null;
    this.usingOverlayCaptions = false;
    this.renderer.setCues([]);
    setOverlayCaptionsClass(false);
    this.renderChapterMarks();
    this.updateCcState();
    this.renderCcMenu();
    this.onCaptionChange?.();
  }

  async refresh(): Promise<void> {
    if (this.disposed) return;
    if (this.refreshInFlight) {
      this.refreshQueued = true;
      return;
    }
    this.refreshInFlight = true;
    const previousId = this.mediaId;
    try {
      try {
        await this.adapter.reload?.();
        this.mediaId = this.adapter.mediaId?.() || null;
        this.tracks = await this.adapter.listCaptionTracks();
        this.chapters = this.adapter.getChapters ? await this.adapter.getChapters() : [];
      } catch (err) {
        console.error('[Theater Everywhere] Media features probe failed:', err);
        this.tracks = [];
        this.chapters = [];
      }
      if (this.disposed) return;
      const mediaChanged = Boolean(previousId && this.mediaId && previousId !== this.mediaId);
      if (mediaChanged) {
        this.activateGeneration += 1;
        this.activeTrackId = null;
        this.usingOverlayCaptions = false;
        this.renderer.setCues([]);
        setOverlayCaptionsClass(false);
      }
      this.renderChapterMarks();
      this.updateCcState();
      this.renderCcMenu();
      const shouldRestoreCaptions = Boolean(this.captionPreference)
        && !this.activateInFlight
        && (mediaChanged || !this.captionsAreOn());
      if (shouldRestoreCaptions) {
        let match = pickCaptionTrack(this.tracks, this.captionPreference);
        if (!match) {
          await new Promise<void>((resolve) => setTimeout(resolve, 700));
          if (this.disposed || !this.captionPreference) return;
          try {
            this.tracks = await this.adapter.listCaptionTracks();
          } catch {
            this.tracks = [];
          }
          this.updateCcState();
          this.renderCcMenu();
          match = pickCaptionTrack(this.tracks, this.captionPreference);
        }
        if (match) {
          await this.activate(match.id, { persist: false, hud: 'on' });
          if (!this.usingOverlayCaptions && !this.disposed) {
            await new Promise<void>((resolve) => setTimeout(resolve, 700));
            if (!this.disposed && this.captionPreference) {
              await this.activate(match.id, { persist: false, hud: 'on' });
            }
          }
        }
      }
    } finally {
      this.refreshInFlight = false;
      if (this.refreshQueued && !this.disposed) {
        this.refreshQueued = false;
        await this.refresh();
      }
    }
  }

  private renderChapterMarks(): void {
    this.chapterLayer.replaceChildren();
    if (typeof document === 'undefined') return;
    const duration = this.video.duration;
    if (!Number.isFinite(duration) || duration <= 0 || this.chapters.length === 0) return;
    for (const chapter of this.chapters) {
      if (chapter.start <= 0) continue;
      const mark = document.createElement('div');
      mark.className = 'theater-scrubber-chapter-mark';
      mark.style.left = `${(chapter.start / duration) * 100}%`;
      this.chapterLayer.appendChild(mark);
    }
  }

  private captionsAreOn(): boolean {
    return this.activeTrackId !== null && this.usingOverlayCaptions;
  }

  private updateCcState(): void {
    const hasTracks = this.tracks.length > 0;
    this.ccBtn.classList.toggle('disabled', !hasTracks);
    this.ccBtn.style.opacity = hasTracks ? '' : '0.35';
    this.ccBtn.style.pointerEvents = hasTracks ? '' : 'none';
    this.ccBtn.classList.toggle('active', this.captionsAreOn());
  }

  setCaptionStyle(style: CaptionStyle): void {
    this.captionStyle = style;
    this.renderer.setStyle(style);
  }

  renderCcMenu(): void {
    if (typeof document === 'undefined') return;
    this.ccMenu.replaceChildren();

    const header = document.createElement('div');
    header.className = 'theater-cc-menu-header';
    const title = document.createElement('span');
    title.className = 'theater-cc-menu-title';
    title.textContent = this.t('subtitlesMenuTitle');
    const optionsBtn = document.createElement('button');
    optionsBtn.type = 'button';
    optionsBtn.className = 'theater-cc-menu-options';
    optionsBtn.textContent = this.t('subtitleOptions');
    optionsBtn.addEventListener('click', (event) => {
      event.stopPropagation();
      void this.openCaptionOptions();
    });
    header.append(title, optionsBtn);

    const list = document.createElement('div');
    list.className = 'theater-cc-menu-list';
    list.appendChild(header);

    if (this.tracks.length === 0) {
      const item = document.createElement('div');
      item.className = 'theater-cc-menu-item';
      item.textContent = this.t('noSubtitles');
      item.style.opacity = '0.5';
      item.style.cursor = 'default';
      list.appendChild(item);
      this.ccMenu.appendChild(list);
      return;
    }

    list.appendChild(this.menuItem(this.t('subtitlesOff'), !this.captionsAreOn(), () => {
      void this.activate(null, { hud: true });
    }));

    for (const track of this.tracks) {
      const label = this.captionTrackDisplayLabel(track);
      list.appendChild(this.menuItem(label, this.captionsAreOn() && this.activeTrackId === track.id, () => {
        void this.activate(track.id, { hud: true });
      }));
    }
    this.ccMenu.appendChild(list);
  }

  private captionTrackDisplayLabel(track: CaptionTrack): string {
    const baseLabel = track.label || track.language || this.t('trackLabel', '1');
    return track.autoGenerated && !/auto/i.test(baseLabel)
      ? this.t('autoGeneratedTrack', baseLabel)
      : baseLabel;
  }

  private emitCaptionHud(result: CaptionToggleResult, hud?: boolean | 'on'): void {
    if (!this.onCaptionHud) return;
    if (hud === false || hud == null) return;
    if (hud === 'on' && result !== 'on') return;
    const track = result === 'on' && this.activeTrackId
      ? this.tracks.find((item) => item.id === this.activeTrackId)
      : undefined;
    this.onCaptionHud({
      result,
      ...(track ? { label: this.captionTrackDisplayLabel(track) } : {})
    });
  }

  private async openCaptionOptions(): Promise<void> {
    this.ccMenu.classList.remove('visible');
    this.onCaptionChange?.();
    await openCaptionOptionsDialog({
      t: this.t,
      style: this.captionStyle,
      onChange: (style) => {
        this.setCaptionStyle(style);
        this.onCaptionStyleChange?.(style);
      },
      decorate: this.decorateCaptionDialog
    });
  }

  private menuItem(label: string, active: boolean, onClick: () => void): HTMLButtonElement {
    const item = document.createElement('button');
    item.className = 'theater-cc-menu-item';
    item.textContent = label;
    if (active) {
      item.classList.add('active');
      const checkIcon = document.createElement('span');
      checkIcon.textContent = '✓';
      checkIcon.style.marginLeft = '8px';
      item.appendChild(checkIcon);
    }
    item.addEventListener('click', () => {
      onClick();
      this.ccMenu.classList.remove('visible');
    });
    return item;
  }

  private enqueue<T>(fn: () => Promise<T>): Promise<T> {
    const run = this.opChain.then(fn, fn);
    this.opChain = run.then(() => undefined, () => undefined);
    return run;
  }

  private persistAfterActivate(id: string | null, on: boolean, persist: boolean): void {
    const track = on && id ? this.tracks.find((item) => item.id === id) : undefined;
    if (on && track) {
      const language = normalizeLanguageCode(track.language);
      const label = normalizeCaptionLabel(track.label);
      if (!language && !label) return;
      const choice: CaptionLanguageChoice = language
        ? { language, autoGenerated: Boolean(track.autoGenerated) }
        : { language: '', autoGenerated: Boolean(track.autoGenerated), label };
      this.captionPreference = choice;
      this.lastLanguagePref = choice;
      if (persist) {
        this.onCaptionPreferenceChange?.({
          enabled: true,
          ...choice
        });
      }
      return;
    }
    if (id === null) {
      const previous = this.captionPreference || this.lastLanguagePref;
      this.captionPreference = null;
      if (persist) {
        this.onCaptionPreferenceChange?.({
          enabled: false,
          language: previous?.language || '',
          autoGenerated: Boolean(previous?.autoGenerated),
          ...(previous?.label ? { label: previous.label } : {})
        });
      }
    }
  }

  private async activateUnlocked(id: string | null, options?: CaptionActivateOptions): Promise<CaptionToggleResult> {
    if (this.disposed) return this.captionsAreOn() ? 'on' : 'off';
    const gen = ++this.activateGeneration;
    this.activateInFlight = true;
    const persist = options?.persist !== false;
    try {
      let overlayCues: Awaited<ReturnType<MediaFeaturesAdapter['activateCaptionTrack']>> = [];
      try {
        overlayCues = await this.adapter.activateCaptionTrack(id);
      } catch (err) {
        console.error('[Theater Everywhere] Caption activate failed:', err);
        overlayCues = [];
      }
      if (this.disposed || gen !== this.activateGeneration) {
        return this.captionsAreOn() ? 'on' : 'off';
      }
      let on = Boolean(id && overlayCues && overlayCues.length > 0);
      if (id && !on) {
        try {
          await this.adapter.activateCaptionTrack(null);
        } catch (err) {
          console.error('[Theater Everywhere] Caption deactivate failed:', err);
        }
        if (this.disposed || gen !== this.activateGeneration) {
          return this.captionsAreOn() ? 'on' : 'off';
        }
        overlayCues = [];
      }
      this.activeTrackId = on ? id : null;
      this.usingOverlayCaptions = on;
      this.renderer.setCues(on ? overlayCues : []);
      setOverlayCaptionsClass(on);
      if (on) this.renderer.update(displayMediaTime(this.video));
      this.persistAfterActivate(id, on, persist);
      this.updateCcState();
      this.renderCcMenu();
      this.onCaptionChange?.();
      if (!id) return 'off';
      return on ? 'on' : 'failed';
    } finally {
      this.activateInFlight = false;
      if (gen !== this.activateGeneration && !this.disposed) {
        void this.refresh();
      }
    }
  }

  async activate(id: string | null, options?: CaptionActivateOptions): Promise<CaptionToggleResult> {
    const result = await this.enqueue(() => this.activateUnlocked(id, options));
    this.emitCaptionHud(result, options?.hud);
    return result;
  }

  async toggleCaptions(): Promise<CaptionToggleResult> {
    return this.enqueue(async () => {
      if (this.disposed || this.tracks.length === 0) {
        this.emitCaptionHud('none', true);
        return 'none';
      }
      if (this.captionsAreOn()) {
        const result = await this.activateUnlocked(null);
        this.emitCaptionHud(result, true);
        return this.captionsAreOn() ? 'on' : 'off';
      }
      const match = pickCaptionTrack(this.tracks, this.lastLanguagePref || this.captionPreference);
      if (!match) {
        this.emitCaptionHud('none', true);
        return 'none';
      }
      const result = await this.activateUnlocked(match.id);
      this.emitCaptionHud(result, true);
      return this.captionsAreOn() ? 'on' : 'failed';
    });
  }

  updateTime(time: number): void {
    if (this.usingOverlayCaptions) this.renderer.update(time);
  }

  retainCaptionsOnElementReset(): boolean {
    const pageId = this.adapter.mediaId?.() || null;
    return Boolean(pageId && this.mediaId && pageId === this.mediaId);
  }

  tooltipExtras(time: number): TooltipMediaExtras {
    const chapter = chapterAtTime(this.chapters, time);
    const preview = this.adapter.getPreviewFrame?.(time, this.video.duration || 0) || null;
    return {
      chapterTitle: chapter?.title || '',
      preview
    };
  }

  ccTooltip(): string {
    if (this.tracks.length === 0) return this.t('noSubtitlesAvailable');
    return this.captionsAreOn() ? this.t('disableSubtitles') : this.t('enableSubtitles');
  }

  dispose(): void {
    this.disposed = true;
    this.activateGeneration += 1;
    this.refreshQueued = false;
    setOverlayCaptionsClass(false);
    this.renderer.dispose();
    this.adapter.dispose();
    this.chapterLayer.remove();
  }
}
