import { parseCaptionPayload } from './parsers/captions';
import { parseYoutubeDescriptionChapters } from './parsers/youtube-chapters';
import { getMuxPreviewFrame, parseMuxStoryboard, type MuxStoryboardSet } from './parsers/mux-storyboard';
import {
  applyPatreonCaptionMeta,
  mergePatreonCaptionTracks,
  parsePatreonPageAssets,
  pickPatreonPageAssets,
  captionLooksAutoGenerated,
  type PatreonPageCaption
} from './parsers/patreon-page';
import { isAllowedMediaFetchUrl, type MediaFetchRequest } from './fetch-allowlist';
import { requestMediaProbe, requestPageFetch, type PatreonPlayerSnapshot } from './probe';
import type {
  CaptionCue,
  CaptionTrack,
  Chapter,
  MediaCapabilities,
  MediaFeaturesAdapter,
  PreviewFrame,
  PreviewSource
} from './types';

const cueCache = new Map<string, CaptionCue[]>();

function looksLikeStoryboardBody(body: string): boolean {
  const start = body.trim().slice(0, 80);
  if (/^WEBVTT/i.test(start)) return true;
  if (start.startsWith('{') && /"tiles"\s*:/.test(body.slice(0, 400))) return true;
  return false;
}

function looksLikeCaptionBody(body: string): boolean {
  const start = body.trim().slice(0, 80).toLowerCase();
  if (start.startsWith('<!doctype') || start.startsWith('<html')) return false;
  return /^WEBVTT/i.test(body.trim()) || parseCaptionPayload(body).length > 0;
}

async function fetchPatreonMedia(url: string, kind: MediaFetchRequest['kind']): Promise<string | null> {
  let absolute = url;
  try {
    absolute = new URL(url, window.location.href).toString();
  } catch {
    return null;
  }
  const request: MediaFetchRequest = { provider: 'patreon', kind, url: absolute };
  if (!isAllowedMediaFetchUrl(request)) return null;

  const fromPage = await requestPageFetch(absolute, 15000);
  if (fromPage) {
    if (kind === 'caption-track' ? looksLikeCaptionBody(fromPage) : looksLikeStoryboardBody(fromPage)) {
      return fromPage;
    }
  }

  try {
    const response = await fetch(absolute, { credentials: 'omit' });
    if (response.ok) {
      const text = await response.text();
      if (kind === 'caption-track' ? looksLikeCaptionBody(text) : looksLikeStoryboardBody(text)) return text;
    }
  } catch {
    // Fall through to the extension broker when page CORS blocks the request.
  }

  try {
    const result = await chrome.runtime.sendMessage({
      action: 'theater-fetch-media',
      ...request
    });
    const body = typeof result?.body === 'string' ? result.body : null;
    if (!result?.ok || !body) return null;
    if (kind === 'caption-track' ? looksLikeCaptionBody(body) : looksLikeStoryboardBody(body)) return body;
  } catch {
    return null;
  }
  return null;
}

function pageAssetsFromDocument(playbackId?: string) {
  const html = typeof document === 'undefined' ? '' : document.documentElement?.innerHTML || '';
  return pickPatreonPageAssets(parsePatreonPageAssets(html), playbackId);
}

function readPageCaptionMeta(): Array<{ language: string; label: string; autoGenerated: boolean }> {
  if (typeof document === 'undefined') return [];
  const video = document.querySelector('video.theater-everywhere-video-active, video[data-theater-everywhere]')
    || document.querySelector('video');
  if (!(video instanceof HTMLVideoElement) || !video.textTracks) return [];
  const meta: Array<{ language: string; label: string; autoGenerated: boolean }> = [];
  for (let i = 0; i < video.textTracks.length; i++) {
    const track = video.textTracks[i];
    const kind = track.kind as string;
    if (kind && kind !== 'subtitles' && kind !== 'captions' && kind !== '') continue;
    const language = track.language || '';
    const label = track.label || '';
    if (!language && !label) continue;
    meta.push({
      language,
      label,
      autoGenerated: captionLooksAutoGenerated(label)
    });
  }
  return meta;
}

export class PatreonAdapter implements MediaFeaturesAdapter {
  private snapshot: PatreonPlayerSnapshot | null = null;
  private storyboard: MuxStoryboardSet | null = null;
  private tracks: PatreonPageCaption[] = [];

  async load(): Promise<void> {
    const probed = await requestMediaProbe();
    const page = pageAssetsFromDocument(probed.patreon?.playbackId);
    const captionTracks = applyPatreonCaptionMeta(
      mergePatreonCaptionTracks(probed.patreon?.captionTracks, page?.captions),
      readPageCaptionMeta()
    );
    this.snapshot = {
      playbackId: probed.patreon?.playbackId || page?.playbackId,
      duration: probed.patreon?.duration,
      storyboardUrl: page?.storyboardVttUrl || page?.storyboardJsonUrl || probed.patreon?.storyboardUrl,
      description: probed.patreon?.description,
      chapters: probed.patreon?.chapters,
      captionTracks
    };
    this.tracks = captionTracks;
    this.storyboard = null;
    const url = this.snapshot.storyboardUrl;
    if (!url) return;
    const kind = /\.json(\?|$)/i.test(url) ? 'storyboard-json' : 'storyboard-vtt';
    const body = await fetchPatreonMedia(url, kind);
    this.storyboard = body ? parseMuxStoryboard(body) : null;
  }

  async probe(): Promise<MediaCapabilities> {
    if (!this.snapshot) await this.load();
    const muxChapters = this.snapshot?.chapters || [];
    const descriptionChapters = parseYoutubeDescriptionChapters(
      this.snapshot?.description || '',
      this.snapshot?.duration
    );
    return {
      captions: this.tracks.length > 0,
      chapters: muxChapters.length > 0 || descriptionChapters.length > 0,
      previews: Boolean(this.storyboard)
    };
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    if (!this.snapshot) await this.load();
    return this.tracks.map((track) => ({
      id: track.id,
      language: track.language,
      label: track.label || track.language || 'Captions',
      kind: 'captions' as const,
      source: 'patreon' as const,
      autoGenerated: Boolean(track.autoGenerated || captionLooksAutoGenerated(track.label || ''))
    }));
  }

  async activateCaptionTrack(id: string | null): Promise<CaptionCue[] | null> {
    if (id === null) return null;
    if (!this.snapshot) await this.load();
    const track = this.tracks.find((item) => item.id === id);
    if (!track) return null;
    const cached = cueCache.get(track.url);
    if (cached && cached.length > 0) return cached;
    const body = await fetchPatreonMedia(track.url, 'caption-track');
    if (!body) return [];
    const cues = parseCaptionPayload(body);
    if (cues.length > 0) cueCache.set(track.url, cues);
    return cues;
  }

  async getChapters(): Promise<Chapter[]> {
    if (!this.snapshot) await this.load();
    const duration = this.snapshot?.duration;
    const muxChapters = (this.snapshot?.chapters || [])
      .filter((chapter) => typeof chapter.startTime === 'number' && chapter.title)
      .sort((a, b) => (a.startTime || 0) - (b.startTime || 0));
    if (muxChapters.length > 0) {
      return muxChapters.map((chapter, index, all) => ({
        start: chapter.startTime || 0,
        end: all[index + 1]?.startTime ?? duration,
        title: String(chapter.title),
        source: 'patreon',
        confidence: 'high' as const
      }));
    }
    return parseYoutubeDescriptionChapters(this.snapshot?.description || '', duration).map((chapter) => ({
      ...chapter,
      source: 'patreon'
    }));
  }

  async getPreviewSource(): Promise<PreviewSource> {
    if (!this.snapshot) await this.load();
    return this.storyboard
      ? { kind: 'sprite', provider: 'patreon' }
      : { kind: 'none', reason: 'no-storyboard' };
  }

  getPreviewFrame(time: number, _duration: number): PreviewFrame | null {
    if (!this.storyboard) return null;
    return getMuxPreviewFrame(this.storyboard, time);
  }

  mediaId(): string | null {
    return this.snapshot?.playbackId || null;
  }

  async reload(): Promise<void> {
    this.snapshot = null;
    this.storyboard = null;
    this.tracks = [];
    await this.load();
  }

  invalidate(): void {
    this.snapshot = null;
    this.storyboard = null;
    this.tracks = [];
    cueCache.clear();
  }

  dispose(): void {
    this.snapshot = null;
    this.storyboard = null;
    this.tracks = [];
  }
}

export { isPatreonHost } from '../providers/hosts';
