import { sanitizeContentTitle } from './content-title';
import { readYoutubePlayerMetadata, youtubeRecord } from './parsers/youtube-player-response';
import { findYoutubeChapterMarkers } from './parsers/youtube-chapters';
import { createWorldMessage, isSameWindowMessage, readWorldEnvelope } from '../protocol/world-messages';
import type { BilibiliSnapshot } from './parsers/bilibili';
import type { BilibiliIntlSnapshot } from '../providers/bilibili-intl/main';
import type { TencentSnapshot } from '../providers/tencent/main';
import type { CrunchyrollSnapshot } from '../providers/crunchyroll/main';

export const MEDIA_PROBE_EVENT = 'theater-everywhere-media-probe';
export const MEDIA_PROBE_RESULT_EVENT = 'theater-everywhere-media-probe-result';
export const MEDIA_FETCH_EVENT = 'theater-everywhere-media-fetch';
export const MEDIA_FETCH_RESULT_EVENT = 'theater-everywhere-media-fetch-result';
export const MEDIA_YT_CAPTIONS_EVENT = 'theater-everywhere-youtube-captions';
export const MEDIA_YT_CAPTIONS_RESULT_EVENT = 'theater-everywhere-youtube-captions-result';

export type YoutubeCaptionMeta = {
  id: string;
  language: string;
  label: string;
  kind: 'captions' | 'subtitles';
  autoGenerated: boolean;
  baseUrl: string;
};

export type YoutubePlayerSnapshot = {
  videoId?: string;
  title?: string;
  duration?: number;
  description?: string;
  captionTracks?: YoutubeCaptionMeta[];
  storyboardSpec?: string;
  markers?: Array<{ startMillis?: number; title?: { simpleText?: string } | string }>;
  heatmap?: {
    source: 'markers' | 'legacy' | 'svg';
    segments?: Array<{ startMs: number; durationMs: number; intensity: number }>;
    svgPath?: string;
    floor?: number;
  };
};

export type VimeoThumbPreview = {
  url: string;
  width: number;
  height: number;
  frameWidth: number;
  frameHeight: number;
  columns: number;
  frames: number;
};

export type VimeoPlayerSnapshot = {
  duration?: number;
  videoId?: string;
  title?: string;
  textTracks?: Array<{ id?: string | number; label?: string; language?: string; kind?: string }>;
  chapters?: Array<{ startTime?: number; title?: string }>;
  thumbPreview?: VimeoThumbPreview;
};

export type PatreonCaptionMeta = {
  id: string;
  language: string;
  label: string;
  kind?: 'captions' | 'subtitles';
  url: string;
  autoGenerated?: boolean;
};

export type PatreonPlayerSnapshot = {
  playbackId?: string;
  title?: string;
  duration?: number;
  storyboardUrl?: string;
  description?: string;
  chapters?: Array<{ startTime?: number; title?: string }>;
  captionTracks?: PatreonCaptionMeta[];
};

export type TwitchCaptionMeta = {
  id: string;
  language: string;
  label: string;
  kind?: 'captions' | 'subtitles';
  url?: string;
  autoGenerated?: boolean;
  delivery?: 'overlay' | 'host';
};

export type TwitchPlayerSnapshot = {
  videoId?: string;
  title?: string;
  duration?: number;
  seekPreviewsURL?: string;
  moments?: Array<{ startTime?: number; endTime?: number; title?: string }>;
  captionTracks?: TwitchCaptionMeta[];
};

export type DisneyCaptionMeta = {
  id: string;
  language: string;
  label: string;
  url: string;
};

export type DisneyPlayerSnapshot = {
  mediaId?: string;
  title?: string;
  duration?: number;
  masterUrl?: string;
  storyboardUrl?: string;
  bifBlobUrl?: string;
  thumbnail?: {
    width: number;
    height: number;
    intervalMs: number;
    bifUrl?: string;
  };
  captionTracks?: DisneyCaptionMeta[];
};

export type NetflixProbeSnapshot = {
  videoId?: string;
  title?: string;
  tracks?: Array<{
    id: string;
    language: string;
    label: string;
    kind?: string;
    forced?: boolean;
    none?: boolean;
  }>;
  selectedTrackId?: string;
};

export type MediaProbeSnapshot = {
  youtube?: YoutubePlayerSnapshot | null;
  vimeo?: VimeoPlayerSnapshot | null;
  patreon?: PatreonPlayerSnapshot | null;
  twitch?: TwitchPlayerSnapshot | null;
  disney?: DisneyPlayerSnapshot | null;
  netflix?: NetflixProbeSnapshot | null;
  bilibili?: BilibiliSnapshot | null;
  bilibiliIntl?: BilibiliIntlSnapshot | null;
  tencent?: TencentSnapshot | null;
  crunchyroll?: CrunchyrollSnapshot | null;
};

type ProbeRequest = {
  requestId: number;
};

type ProbeResponse = ProbeRequest & MediaProbeSnapshot;

let requestId = 0;

export function requestMediaProbe(timeoutMs = 800, provider?: 'bilibili' | 'bilibiliIntl'): Promise<MediaProbeSnapshot> {
  return new Promise((resolve) => {
    const id = ++requestId;
    let settled = false;
    const timer = window.setTimeout(() => finish({}), timeoutMs);

    const onResult = (event: Event) => {
      const detail = (event as CustomEvent<ProbeResponse>).detail;
      if (!detail || detail.requestId !== id) return;
      finish(detail);
    };

    const finish = (snapshot: MediaProbeSnapshot) => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timer);
      window.removeEventListener(resultEvent, onResult as EventListener);
      resolve({
        youtube: normalizeYoutubeSnapshot(snapshot.youtube),
        vimeo: snapshot.vimeo ?? null,
        patreon: snapshot.patreon ?? null,
        twitch: snapshot.twitch ?? null,
        disney: snapshot.disney ?? null,
        netflix: snapshot.netflix ?? null,
        bilibili: snapshot.bilibili ?? null,
        bilibiliIntl: snapshot.bilibiliIntl ?? null,
        tencent: snapshot.tencent ?? null,
        crunchyroll: snapshot.crunchyroll ?? null
      });
    };

    const resultEvent = provider === 'bilibili'
      ? 'theater-everywhere-bilibili-probe-result'
      : provider === 'bilibiliIntl'
        ? 'theater-everywhere-bilibili-intl-probe-result'
        : MEDIA_PROBE_RESULT_EVENT;
    window.addEventListener(resultEvent, onResult as EventListener);
    window.dispatchEvent(new CustomEvent<ProbeRequest>(MEDIA_PROBE_EVENT, { detail: { requestId: id } }));
  });
}

/**
 * Requests a page resource through the MAIN-world broker.
 * Resolves to `null` when the broker rejects the request, returns an empty body, or times out.
 */
export function requestPageFetch(url: string, timeoutMs = 8000): Promise<string | null> {
  return new Promise((resolve) => {
    const request = createWorldMessage('PAGE_FETCH', { url });
    let settled = false;

    const onMessage = (event: MessageEvent) => {
      if (!isSameWindowMessage(event)) return;
      const envelope = readWorldEnvelope(event.data);
      if (!envelope || envelope.type !== 'PAGE_FETCH_RESULT') return;
      if (envelope.requestId !== request.requestId) return;
      const body = envelope.payload.body;
      finish(envelope.payload.ok && typeof body === 'string' ? body : null);
    };

    const finish = (body: string | null) => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timer);
      window.removeEventListener('message', onMessage);
      resolve(body && body.trim() ? body : null);
    };

    const timer = window.setTimeout(() => finish(null), timeoutMs);
    window.addEventListener('message', onMessage);
    window.postMessage(request, '*');
  });
}

export type YoutubeCaptionsRequest = {
  enabled: boolean;
  language?: string;
  kind?: string | null;
};

export function requestYoutubePlayerCaptions(options: YoutubeCaptionsRequest, timeoutMs = 3000): Promise<boolean> {
  return new Promise((resolve) => {
    const id = ++requestId;
    let settled = false;
    const timer = window.setTimeout(() => finish(false), timeoutMs);

    const onResult = (event: Event) => {
      const detail = youtubeRecord((event as CustomEvent<unknown>).detail);
      if (!detail || detail.requestId !== id) return;
      finish(detail.ok === true);
    };

    const finish = (ok: boolean) => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timer);
      window.removeEventListener(MEDIA_YT_CAPTIONS_RESULT_EVENT, onResult as EventListener);
      resolve(ok);
    };

    window.addEventListener(MEDIA_YT_CAPTIONS_RESULT_EVENT, onResult as EventListener);
    window.dispatchEvent(new CustomEvent(MEDIA_YT_CAPTIONS_EVENT, {
      detail: { requestId: id, ...options }
    }));
  });
}

export function readYoutubeSnapshotFromDom(): YoutubePlayerSnapshot | null {
  const scripts = Array.from(document.querySelectorAll('script'));
  for (const script of scripts) {
    const text = script.textContent || '';
    if (!text.includes('ytInitialPlayerResponse')) continue;
    const match = text.match(/ytInitialPlayerResponse\s*=\s*(\{[\s\S]*?\});/);
    if (!match) continue;
    try {
      return normalizeYoutubePlayerResponse(JSON.parse(match[1]));
    } catch {
      continue;
    }
  }
  return null;
}

function normalizeYoutubeHeatmap(raw: unknown): YoutubePlayerSnapshot['heatmap'] | undefined {
  if (!raw || typeof raw !== 'object') return undefined;
  const data = raw as {
    source?: unknown;
    segments?: unknown;
    svgPath?: unknown;
    floor?: unknown;
  };
  const source = data.source;
  if (source !== 'markers' && source !== 'legacy' && source !== 'svg') return undefined;
  const segments = Array.isArray(data.segments)
    ? data.segments.flatMap((item) => {
      if (!item || typeof item !== 'object') return [];
      const row = item as { startMs?: unknown; durationMs?: unknown; intensity?: unknown };
      const startMs = typeof row.startMs === 'number' ? row.startMs : NaN;
      const durationMs = typeof row.durationMs === 'number' ? row.durationMs : NaN;
      const intensity = typeof row.intensity === 'number' ? row.intensity : NaN;
      if (!Number.isFinite(startMs) || !Number.isFinite(durationMs) || !Number.isFinite(intensity)) return [];
      if (startMs < 0 || durationMs <= 0) return [];
      return [{ startMs, durationMs, intensity }];
    })
    : undefined;
  const svgPath = typeof data.svgPath === 'string' && data.svgPath.trim().length > 20
    ? data.svgPath.trim()
    : undefined;
  const floor = typeof data.floor === 'number' ? data.floor : NaN;
  const usableFloor = Number.isFinite(floor) && floor > 0 && floor < 1 ? floor : undefined;
  if (!segments?.length && !svgPath) return undefined;
  return {
    source,
    ...(segments && segments.length > 0 ? { segments } : {}),
    ...(svgPath ? { svgPath } : {}),
    ...(usableFloor ? { floor: usableFloor } : {})
  };
}

export function normalizeYoutubePlayerResponse(raw: unknown): YoutubePlayerSnapshot | null {
  const metadata = readYoutubePlayerMetadata(raw);
  if (!metadata) return null;
  return {
    ...metadata,
    markers: findYoutubeChapterMarkers(raw),
    heatmap: normalizeYoutubeHeatmap(youtubeRecord(raw)?.heatmap)
  };
}

/** Validates the already-normalized DOM and event bridge snapshot separately from host responses. */
export function normalizeYoutubeSnapshot(raw: unknown): YoutubePlayerSnapshot | null {
  const data = youtubeRecord(raw);
  if (!data) return null;
  const captions: unknown[] = Array.isArray(data.captionTracks) ? data.captionTracks : [];
  const captionTracks = captions.slice(0, 40).flatMap((value, index): YoutubeCaptionMeta[] => {
    const track = youtubeRecord(value);
    if (!track || typeof track.baseUrl !== 'string' || !track.baseUrl || track.baseUrl.length > 32000) return [];
    const language = typeof track.language === 'string' ? track.language.slice(0, 16) : '';
    return [{
      id: typeof track.id === 'string' ? track.id.slice(0, 48) : `youtube:${language || index}`,
      language,
      label: typeof track.label === 'string' ? track.label.slice(0, 80) : language,
      kind: track.kind === 'captions' ? 'captions' : 'subtitles',
      autoGenerated: track.autoGenerated === true,
      baseUrl: track.baseUrl
    }];
  });
  return {
    videoId: typeof data.videoId === 'string' ? data.videoId.slice(0, 20) : undefined,
    title: sanitizeContentTitle(data.title) || undefined,
    duration: typeof data.duration === 'number' && Number.isFinite(data.duration) && data.duration > 0 ? data.duration : undefined,
    description: typeof data.description === 'string' ? data.description.slice(0, 20000) : undefined,
    captionTracks,
    storyboardSpec: typeof data.storyboardSpec === 'string' ? data.storyboardSpec.slice(0, 4000) : undefined,
    markers: findYoutubeChapterMarkers({ markersMap: [{ chapters: data.markers }] }),
    heatmap: normalizeYoutubeHeatmap(data.heatmap)
  };
}
