export const MEDIA_PROBE_EVENT = 'theater-everywhere-media-probe';
export const MEDIA_PROBE_RESULT_EVENT = 'theater-everywhere-media-probe-result';
export const MEDIA_FETCH_EVENT = 'theater-everywhere-media-fetch';
export const MEDIA_FETCH_RESULT_EVENT = 'theater-everywhere-media-fetch-result';
export const MEDIA_YT_CAPTIONS_EVENT = 'theater-everywhere-youtube-captions';
export const MEDIA_YT_CAPTIONS_RESULT_EVENT = 'theater-everywhere-youtube-captions-result';

export type YoutubeCaptionMeta = {
  id: string;
  language: string;
  label: string;
  kind: 'captions' | 'subtitles';
  autoGenerated: boolean;
  baseUrl: string;
};

export type YoutubePlayerSnapshot = {
  videoId?: string;
  duration?: number;
  description?: string;
  captionTracks?: YoutubeCaptionMeta[];
  storyboardSpec?: string;
  markers?: Array<{ startMillis?: number; title?: { simpleText?: string } | string }>;
};

export type VimeoThumbPreview = {
  url: string;
  width: number;
  height: number;
  frameWidth: number;
  frameHeight: number;
  columns: number;
  frames: number;
};

export type VimeoPlayerSnapshot = {
  duration?: number;
  videoId?: string;
  textTracks?: Array<{ id?: string | number; label?: string; language?: string; kind?: string }>;
  chapters?: Array<{ startTime?: number; title?: string }>;
  thumbPreview?: VimeoThumbPreview;
};

export type PatreonCaptionMeta = {
  id: string;
  language: string;
  label: string;
  kind?: 'captions' | 'subtitles';
  url: string;
  autoGenerated?: boolean;
};

export type PatreonPlayerSnapshot = {
  playbackId?: string;
  duration?: number;
  storyboardUrl?: string;
  description?: string;
  chapters?: Array<{ startTime?: number; title?: string }>;
  captionTracks?: PatreonCaptionMeta[];
};

export type TwitchCaptionMeta = {
  id: string;
  language: string;
  label: string;
  kind?: 'captions' | 'subtitles';
  url: string;
  autoGenerated?: boolean;
};

export type TwitchPlayerSnapshot = {
  videoId?: string;
  duration?: number;
  seekPreviewsURL?: string;
  moments?: Array<{ startTime?: number; endTime?: number; title?: string }>;
  captionTracks?: TwitchCaptionMeta[];
};

export type DisneyCaptionMeta = {
  id: string;
  language: string;
  label: string;
  url: string;
};

export type DisneyPlayerSnapshot = {
  mediaId?: string;
  duration?: number;
  masterUrl?: string;
  storyboardUrl?: string;
  bifBlobUrl?: string;
  thumbnail?: {
    width: number;
    height: number;
    intervalMs: number;
    bifUrl?: string;
  };
  captionTracks?: DisneyCaptionMeta[];
};

export type MediaProbeSnapshot = {
  youtube?: YoutubePlayerSnapshot | null;
  vimeo?: VimeoPlayerSnapshot | null;
  patreon?: PatreonPlayerSnapshot | null;
  twitch?: TwitchPlayerSnapshot | null;
  disney?: DisneyPlayerSnapshot | null;
};

type ProbeRequest = {
  requestId: number;
};

type ProbeResponse = ProbeRequest & MediaProbeSnapshot;

let requestId = 0;

export function requestMediaProbe(timeoutMs = 800): Promise<MediaProbeSnapshot> {
  return new Promise((resolve) => {
    const id = ++requestId;
    let settled = false;
    const timer = window.setTimeout(() => finish({}), timeoutMs);

    const onResult = (event: Event) => {
      const detail = (event as CustomEvent<ProbeResponse>).detail;
      if (!detail || detail.requestId !== id) return;
      finish(detail);
    };

    const finish = (snapshot: MediaProbeSnapshot) => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timer);
      window.removeEventListener(MEDIA_PROBE_RESULT_EVENT, onResult as EventListener);
      resolve({
        youtube: snapshot.youtube ?? null,
        vimeo: snapshot.vimeo ?? null,
        patreon: snapshot.patreon ?? null,
        twitch: snapshot.twitch ?? null,
        disney: snapshot.disney ?? null
      });
    };

    window.addEventListener(MEDIA_PROBE_RESULT_EVENT, onResult as EventListener);
    window.dispatchEvent(new CustomEvent<ProbeRequest>(MEDIA_PROBE_EVENT, { detail: { requestId: id } }));
  });
}

type FetchRequest = {
  requestId: number;
  url: string;
};

type FetchResponse = {
  requestId: number;
  ok: boolean;
  body?: string;
};

export function requestPageFetch(url: string, timeoutMs = 8000): Promise<string | null> {
  return new Promise((resolve) => {
    const id = ++requestId;
    let settled = false;
    const job = document.createElement('div');
    job.hidden = true;
    job.dataset.teCaptionFetch = 'pending';
    job.dataset.teCaptionId = String(id);
    job.dataset.teCaptionUrl = url;
    document.documentElement.appendChild(job);

    const readJob = (): void => {
      const state = job.dataset.teCaptionFetch;
      if (state === 'ok') finish(job.textContent);
      else if (state === 'err') finish(null);
    };

    const onResult = (event: Event) => {
      const detail = (event as CustomEvent<FetchResponse>).detail;
      if (!detail || detail.requestId !== id) return;
      readJob();
    };

    const finish = (body: string | null) => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timer);
      window.clearInterval(poll);
      observer.disconnect();
      window.removeEventListener(MEDIA_FETCH_RESULT_EVENT, onResult as EventListener);
      job.remove();
      resolve(body && body.trim() ? body : null);
    };

    const timer = window.setTimeout(() => finish(null), timeoutMs);
    const observer = new MutationObserver(readJob);
    observer.observe(job, { attributes: true, attributeFilter: ['data-te-caption-fetch'] });
    const poll = window.setInterval(readJob, 50);

    window.addEventListener(MEDIA_FETCH_RESULT_EVENT, onResult as EventListener);
    window.dispatchEvent(new CustomEvent<FetchRequest>(MEDIA_FETCH_EVENT, { detail: { requestId: id, url } }));
    window.postMessage({ type: MEDIA_FETCH_EVENT, requestId: id }, '*');
  });
}

export type YoutubeCaptionsRequest = {
  enabled: boolean;
  language?: string;
  kind?: string | null;
};

export function requestYoutubePlayerCaptions(options: YoutubeCaptionsRequest, timeoutMs = 800): Promise<boolean> {
  return new Promise((resolve) => {
    const id = ++requestId;
    let settled = false;
    const timer = window.setTimeout(() => finish(false), timeoutMs);

    const onResult = (event: Event) => {
      const detail = (event as CustomEvent<{ requestId?: number; ok?: boolean }>).detail;
      if (!detail || detail.requestId !== id) return;
      finish(Boolean(detail.ok));
    };

    const finish = (ok: boolean) => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timer);
      window.removeEventListener(MEDIA_YT_CAPTIONS_RESULT_EVENT, onResult as EventListener);
      resolve(ok);
    };

    window.addEventListener(MEDIA_YT_CAPTIONS_RESULT_EVENT, onResult as EventListener);
    window.dispatchEvent(new CustomEvent(MEDIA_YT_CAPTIONS_EVENT, {
      detail: { requestId: id, ...options }
    }));
  });
}

export function readYoutubeSnapshotFromDom(): YoutubePlayerSnapshot | null {
  const scripts = Array.from(document.querySelectorAll('script'));
  for (const script of scripts) {
    const text = script.textContent || '';
    if (!text.includes('ytInitialPlayerResponse')) continue;
    const match = text.match(/ytInitialPlayerResponse\s*=\s*(\{[\s\S]*?\});/);
    if (!match) continue;
    try {
      return normalizeYoutubePlayerResponse(JSON.parse(match[1]));
    } catch {
      continue;
    }
  }
  return null;
}

export function normalizeYoutubePlayerResponse(raw: unknown): YoutubePlayerSnapshot | null {
  if (!raw || typeof raw !== 'object') return null;
  const data = raw as Record<string, any>;
  const videoDetails = data.videoDetails || {};
  const captions = data.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
  const markers = data.markersMap
    ? Object.values(data.markersMap as Record<string, any>)
        .flatMap((entry) => entry?.value?.chapters || entry?.chapters || [])
        .map((chapter: any) => ({
          startMillis: Number(chapter?.chapterRenderer?.timeRangeStartMillis ?? chapter?.startMillis),
          title: chapter?.chapterRenderer?.title || chapter?.title
        }))
    : [];

  const captionTracks: YoutubeCaptionMeta[] = captions
    .map((track: any, index: number) => {
      const baseUrl = typeof track?.baseUrl === 'string' ? track.baseUrl : '';
      if (!baseUrl) return null;
      const language = String(track.languageCode || '');
      const label = String(track.name?.simpleText || track.name?.runs?.[0]?.text || language);
      const autoGenerated = track.kind === 'asr';
      return {
        id: `youtube:${track.vssId || language || index}`,
        language,
        label,
        kind: autoGenerated ? 'captions' : 'subtitles',
        autoGenerated,
        baseUrl
      } satisfies YoutubeCaptionMeta;
    })
    .filter(Boolean) as YoutubeCaptionMeta[];

  return {
    videoId: typeof videoDetails.videoId === 'string' ? videoDetails.videoId : undefined,
    duration: Number(videoDetails.lengthSeconds) || undefined,
    description: typeof videoDetails.shortDescription === 'string' ? videoDetails.shortDescription : undefined,
    captionTracks,
    storyboardSpec: data.storyboards?.playerStoryboardSpecRenderer?.spec,
    markers
  };
}
