export type CaptionWord = {
  start: number;
  end: number;
  text: string;
};

export type CaptionCue = {
  start: number;
  end: number;
  text: string;
  words?: CaptionWord[];
};

export type CaptionActivationResult =
  | { status: 'active'; delivery: 'overlay'; cues: CaptionCue[] }
  | { status: 'active'; delivery: 'host'; cues: [] }
  | { status: 'off'; delivery: 'none'; cues: [] }
  | { status: 'failed'; delivery: 'none'; cues: [] };

/**
 * A deferred cue-window download invoked by the controller after it publishes
 * loading feedback. Creating the callback must not start network work.
 * @returns The provider's activation result for the requested caption window.
 */
export type CaptionCueRefresh = () => Promise<CaptionActivationResult>;

export type CaptionTrackSource =
  | 'native-text-track'
  | 'youtube'
  | 'vimeo'
  | 'dailymotion'
  | 'patreon'
  | 'twitch'
  | 'disney'
  | 'netflix'
  | 'bilibili'
  | 'bilibiliIntl'
  | 'tencent'
  | 'crunchyroll';

export type CaptionTrack = {
  id: string;
  language: string;
  label: string;
  kind: 'captions' | 'subtitles';
  source: CaptionTrackSource;
  autoGenerated?: boolean;
  delivery?: 'overlay' | 'host';
  cues?: CaptionCue[];
};

export type Chapter = {
  start: number;
  end?: number;
  title: string;
  source: string;
  confidence: 'high' | 'medium';
};

export type PreviewFrame = {
  time: number;
  width: number;
  height: number;
  image: {
    kind: 'sprite';
    url: string;
    x: number;
    y: number;
    tileWidth: number;
    tileHeight: number;
    sheetWidth: number;
    sheetHeight: number;
  };
};

export type PreviewSource =
  | { kind: 'sprite'; provider: string }
  | { kind: 'none'; reason: string };

export type MediaCapabilities = {
  captions: boolean;
  chapters: boolean;
  previews: boolean;
};

/** Geometry supplied by a provider that paints its own captions. */
export type HostCaptionLayout = {
  width: number;
  height: number;
  lineHeight?: number;
  rows?: number;
  /** Optional element whose dock motion follows the shared caption policy. */
  motionTarget?: HTMLElement;
};

export interface HostCaptionLayoutSource {
  read(): HostCaptionLayout | null;
  observe?(onChange: () => void): () => void;
  reset?(): void;
}

export type TimelineHeatmap = {
  source: string;
  segments?: Array<{ startMs: number; durationMs: number; intensity: number }>;
  svgPath?: string;
};

export interface MediaFeaturesAdapter {
  readHostCaptionLayout?(): HostCaptionLayout | null;
  observeHostCaptionLayout?(onChange: () => void): () => void;
  probe(): Promise<MediaCapabilities>;
  listCaptionTracks(): Promise<CaptionTrack[]>;
  activateCaptionTrack(id: string | null): Promise<CaptionActivationResult>;
  /**
   * Determines whether the active track needs another cue window, without fetching it.
   * @param id Identifier of the active caption track.
   * @param time Display media time in seconds.
   * @returns A lazy download callback, or null synchronously when no work is needed.
   */
  prepareCaptionCueRefresh?(id: string, time: number): CaptionCueRefresh | null;
  getChapters?(): Promise<Chapter[]>;
  /** Select a provider's chapters independently of the preferred timeline list. */
  getChaptersForSource?(source: string): Promise<Chapter[]>;
  getHeatmap?(): TimelineHeatmap | null;
  getPreviewSource?(): Promise<PreviewSource>;
  getPreviewFrame?(time: number, duration: number): PreviewFrame | null;
  mediaId?(): string | null;
  getTitle?(): string | null;
  reload?(): Promise<void>;
  invalidate?(): void;
  dispose(): void;
}
