export type CaptionWord = {
  start: number;
  end: number;
  text: string;
};

export type CaptionCue = {
  start: number;
  end: number;
  text: string;
  words?: CaptionWord[];
};

export type CaptionTrackSource =
  | 'native-text-track'
  | 'youtube'
  | 'vimeo'
  | 'dailymotion'
  | 'patreon'
  | 'twitch'
  | 'disney';

export type CaptionTrack = {
  id: string;
  language: string;
  label: string;
  kind: 'captions' | 'subtitles';
  source: CaptionTrackSource;
  autoGenerated?: boolean;
  delivery?: 'overlay' | 'host';
  cues?: CaptionCue[];
};

export type Chapter = {
  start: number;
  end?: number;
  title: string;
  source: string;
  confidence: 'high' | 'medium';
};

export type PreviewFrame = {
  time: number;
  width: number;
  height: number;
  image: {
    kind: 'sprite';
    url: string;
    x: number;
    y: number;
    tileWidth: number;
    tileHeight: number;
    sheetWidth: number;
    sheetHeight: number;
  };
};

export type PreviewSource =
  | { kind: 'sprite'; provider: string }
  | { kind: 'none'; reason: string };

export type MediaCapabilities = {
  captions: boolean;
  chapters: boolean;
  previews: boolean;
};

export type TimelineHeatmap = {
  source: string;
  segments?: Array<{ startMs: number; durationMs: number; intensity: number }>;
  svgPath?: string;
};

export interface MediaFeaturesAdapter {
  probe(): Promise<MediaCapabilities>;
  listCaptionTracks(): Promise<CaptionTrack[]>;
  activateCaptionTrack(id: string | null): Promise<CaptionCue[] | null>;
  getChapters?(): Promise<Chapter[]>;
  getHeatmap?(): TimelineHeatmap | null;
  getPreviewSource?(): Promise<PreviewSource>;
  getPreviewFrame?(time: number, duration: number): PreviewFrame | null;
  mediaId?(): string | null;
  reload?(): Promise<void>;
  invalidate?(): void;
  dispose(): void;
}
