import { parseCaptionPayload } from './parsers/captions';
import { parseYoutubeDescriptionChapters, parseYoutubeMarkerChapters } from './parsers/youtube-chapters';
import { getStoryboardFrame, parseStoryboardSpec, type StoryboardSet } from './parsers/youtube-storyboard';
import { isAllowedMediaFetchUrl, type MediaFetchRequest } from './fetch-allowlist';
import {
  normalizeYoutubePlayerResponse,
  readYoutubeSnapshotFromDom,
  requestMediaProbe,
  requestPageFetch,
  requestYoutubePlayerCaptions,
  type YoutubeCaptionMeta,
  type YoutubePlayerSnapshot
} from './probe';
import type {
  CaptionCue,
  CaptionTrack,
  Chapter,
  MediaCapabilities,
  MediaFeaturesAdapter,
  PreviewFrame,
  PreviewSource
} from './types';

const cueCache = new Map<string, CaptionCue[]>();

function looksLikeHtmlError(body: string): boolean {
  const start = body.trim().slice(0, 80).toLowerCase();
  return start.startsWith('<!doctype') || start.startsWith('<html');
}

function usableCaptionBody(body: string | null | undefined): string | null {
  if (!body || !body.trim() || looksLikeHtmlError(body)) return null;
  return body;
}

function withFmt(url: string, fmt: string | null): string {
  try {
    const parsed = new URL(url, window.location.href);
    if (fmt) parsed.searchParams.set('fmt', fmt);
    else parsed.searchParams.delete('fmt');
    return parsed.toString();
  } catch {
    return url;
  }
}

function captionUrlVariants(baseUrl: string): string[] {
  const variants: string[] = [];
  const seen = new Set<string>();
  const add = (url: string) => {
    if (!url || seen.has(url)) return;
    seen.add(url);
    variants.push(url);
  };
  add(withFmt(baseUrl, 'json3'));
  add(baseUrl);
  add(withFmt(baseUrl, 'vtt'));
  add(withFmt(baseUrl, 'srv3'));
  add(withFmt(baseUrl, null));
  return variants;
}

async function fetchCaptionTrack(url: string): Promise<string | null> {
  let absolute = url;
  try {
    absolute = new URL(url, window.location.href).toString();
  } catch {
    return null;
  }
  const request: MediaFetchRequest = {
    provider: 'youtube',
    kind: 'caption-track',
    url: absolute
  };
  if (!isAllowedMediaFetchUrl(request)) return null;

  const fromPage = usableCaptionBody(await requestPageFetch(absolute, 15000));
  if (fromPage) return fromPage;

  try {
    const response = await fetch(absolute, { credentials: 'include' });
    if (response.ok) {
      const text = usableCaptionBody(await response.text());
      if (text) return text;
    }
  } catch {
    // Fall through to the extension broker when page CORS blocks the request.
  }

  try {
    const result = await chrome.runtime.sendMessage({
      action: 'theater-fetch-media',
      ...request
    });
    const body = typeof result?.body === 'string' ? usableCaptionBody(result.body) : null;
    if (result?.ok && body) return body;
  } catch {
    return null;
  }
  return null;
}

export class YouTubeAdapter implements MediaFeaturesAdapter {
  private snapshot: YoutubePlayerSnapshot | null = null;
  private storyboards: StoryboardSet | null = null;
  private tracks: YoutubeCaptionMeta[] = [];

  async load(): Promise<void> {
    const probed = await requestMediaProbe();
    this.snapshot = probed.youtube || readYoutubeSnapshotFromDom();
    if (!this.snapshot && (window as unknown as { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse) {
      this.snapshot = normalizeYoutubePlayerResponse(
        (window as unknown as { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse
      );
    }
    this.tracks = this.snapshot?.captionTracks || [];
    const spec = this.snapshot?.storyboardSpec;
    this.storyboards = spec
      ? parseStoryboardSpec(spec, this.snapshot?.duration || 0)
      : null;
  }

  async probe(): Promise<MediaCapabilities> {
    if (!this.snapshot) await this.load();
    const chapters = await this.getChapters();
    return {
      captions: this.tracks.length > 0,
      chapters: chapters.length > 0,
      previews: Boolean(this.storyboards)
    };
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    if (!this.snapshot) await this.load();
    return this.tracks.map((track) => ({
      id: track.id,
      language: track.language,
      label: track.label,
      kind: track.kind,
      source: 'youtube',
      autoGenerated: track.autoGenerated
    }));
  }

  async activateCaptionTrack(id: string | null): Promise<CaptionCue[] | null> {
    if (id === null) {
      await requestYoutubePlayerCaptions({ enabled: false });
      return null;
    }
    if (!this.snapshot) await this.load();
    const track = this.tracks.find((item) => item.id === id);
    if (!track) return null;
    await requestYoutubePlayerCaptions({
      enabled: true,
      language: track.language,
      kind: track.autoGenerated ? 'asr' : null
    });
    const cached = cueCache.get(track.baseUrl);
    if (cached && cached.length > 0) {
      await requestYoutubePlayerCaptions({ enabled: false });
      return cached;
    }

    for (const url of captionUrlVariants(track.baseUrl)) {
      const body = await fetchCaptionTrack(url);
      if (!body) continue;
      const cues = parseCaptionPayload(body);
      if (cues.length > 0) {
        cueCache.set(track.baseUrl, cues);
        await requestYoutubePlayerCaptions({ enabled: false });
        return cues;
      }
    }
    return [];
  }

  async getChapters(): Promise<Chapter[]> {
    if (!this.snapshot) await this.load();
    const duration = this.snapshot?.duration;
    const fromDescription = parseYoutubeDescriptionChapters(this.snapshot?.description || '', duration);
    if (fromDescription.length > 0) return fromDescription;
    return parseYoutubeMarkerChapters(this.snapshot?.markers || [], duration);
  }

  async getPreviewSource(): Promise<PreviewSource> {
    if (!this.snapshot) await this.load();
    return this.storyboards
      ? { kind: 'sprite', provider: 'youtube' }
      : { kind: 'none', reason: 'no-storyboard' };
  }

  getPreviewFrame(time: number, _duration: number): PreviewFrame | null {
    if (!this.storyboards) return null;
    const targetWidth = Math.round(160 * (window.devicePixelRatio || 1));
    return getStoryboardFrame(this.storyboards, time, targetWidth);
  }

  dispose(): void {
    this.snapshot = null;
    this.storyboards = null;
    this.tracks = [];
  }
}

export function isYouTubeHost(hostname = window.location.hostname): boolean {
  const host = hostname.replace(/^www\./, '');
  return host === 'youtube.com' || host === 'youtu.be' || host === 'youtube-nocookie.com' || host.endsWith('.youtube.com');
}
