import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { normalizeYoutubePlayerResponse } from './probe';

const response = (captionTracks: unknown): unknown => ({
  videoDetails: { videoId: 'video-a', title: ' A video ', lengthSeconds: '120' },
  captions: { playerCaptionsTracklistRenderer: { captionTracks } },
  storyboards: { playerStoryboardSpecRenderer: { spec: 'storyboard' } }
});

describe('YouTube external player responses', () => {
  it('keeps valid metadata when the caption list has an invalid structure', () => {
    for (const tracks of [null, 7, 'tracks', {}, { map: 'invalid' }]) {
      const result = normalizeYoutubePlayerResponse(response(tracks));
      assert.equal(result?.title, 'A video');
      assert.equal(result?.duration, 120);
      assert.deepEqual(result?.captionTracks, []);
    }
  });

  it('skips invalid tracks and preserves manual and generated caption metadata', () => {
    const result = normalizeYoutubePlayerResponse(response([
      null, true, [], 'track', { baseUrl: 7 }, { baseUrl: '' },
      { baseUrl: 'https://www.youtube.com/api/timedtext?v=a', languageCode: 'en', vssId: '.en', name: { runs: [{ text: 'English' }] } },
      { baseUrl: 'https://www.youtube.com/api/timedtext?v=a&kind=asr', languageCode: 'pl', kind: 'asr', name: { simpleText: 'Polski' } }
    ]));
    assert.deepEqual(result?.captionTracks?.map(track => [track.id, track.label, track.kind, track.autoGenerated]), [
      ['youtube:.en', 'English', 'subtitles', false], ['youtube:pl', 'Polski', 'captions', true]
    ]);
  });

  it('does not coerce object labels, invalid numeric values or storyboard structures', () => {
    const result = normalizeYoutubePlayerResponse({
      videoDetails: { videoId: {}, lengthSeconds: 'Infinity', title: { runs: {} }, shortDescription: [] },
      microformat: { playerMicroformatRenderer: { title: { simpleText: 'Fallback' } } },
      captions: { playerCaptionsTracklistRenderer: { captionTracks: [{ baseUrl: 'url', languageCode: {}, vssId: {}, name: { runs: {} } }] } },
      storyboards: { playerStoryboardSpecRenderer: { spec: {} } }
    });
    assert.equal(result?.videoId, undefined);
    assert.equal(result?.duration, undefined);
    assert.equal(result?.storyboardSpec, undefined);
    assert.equal(result?.description, undefined);
    assert.equal(result?.title, 'Fallback');
    assert.equal(result?.captionTracks?.[0].language, '');
    assert.equal(result?.captionTracks?.[0].label, '');
    assert.equal(result?.captionTracks?.[0].id, 'youtube:0');
    for (const raw of [null, [], 'response', 5]) assert.equal(normalizeYoutubePlayerResponse(raw), null);
  });

  it('bounds lists and strings before passing metadata across worlds', () => {
    const result = normalizeYoutubePlayerResponse(response(Array.from({ length: 45 }, () => ({
      baseUrl: 'url', languageCode: 'a'.repeat(30), vssId: 'b'.repeat(100), name: { simpleText: 'c'.repeat(100) }
    }))));
    assert.equal(result?.captionTracks?.length, 40);
    assert.equal(result?.captionTracks?.[0].language.length, 16);
    assert.equal(result?.captionTracks?.[0].id.length, 48);
    assert.equal(result?.captionTracks?.[0].label.length, 80);
    assert.deepEqual(normalizeYoutubePlayerResponse(response([{ baseUrl: 'a'.repeat(32001) }]))?.captionTracks, []);
  });
});

// Heatmaps and response identity are read from the same untrusted player boundary.
it('validates nested response identities and refuses nonnumeric heatmap values', async () => {
  const { youtubeWatchJsonVideoId, findYoutubeHeatmap } = await import('./parsers/youtube-heatmap');
  assert.equal(youtubeWatchJsonVideoId({ playerResponse: { videoDetails: { videoId: 'nested' } } }), 'nested');
  assert.equal(youtubeWatchJsonVideoId({ response: { currentVideoEndpoint: { watchEndpoint: { videoId: 'endpoint' } } } }), 'endpoint');
  for (const raw of [{ videoDetails: [] }, { playerResponse: 'invalid' }, { currentVideoEndpoint: { watchEndpoint: { videoId: {} } } }, []]) {
    assert.equal(youtubeWatchJsonVideoId(raw), null);
  }
  const markers = (startMillis: unknown) => ({ markerType: 'MARKER_TYPE_HEATMAP', markers: [{ startMillis, durationMillis: '1000', intensityScoreNormalized: '0.5' }] });
  for (const invalid of [null, false, [], {}, Symbol('invalid')]) assert.equal(findYoutubeHeatmap(markers(invalid)), null);
  assert.deepEqual(findYoutubeHeatmap(markers('0'))?.segments, [{ startMs: 0, durationMs: 1000, intensity: 0.5 }]);
});

it('validates published normalized snapshots rather than trusting a JSON object cast', async () => {
  const { readPublishedYoutubeSnapshot } = await import('./youtube-snapshot');
  const malformed = readPublishedYoutubeSnapshot({ querySelector: () => ({ textContent: JSON.stringify({
    videoId: 'video-a', title: ' Preserved title ', duration: {}, captionTracks: { map: false },
    storyboardSpec: [], heatmap: { source: 'markers', segments: [{ startMs: null, durationMs: 100, intensity: 0.5 }] }
  }) }) as Element });
  assert.equal(malformed?.title, 'Preserved title');
  assert.equal(malformed?.videoId, 'video-a');
  assert.equal(malformed?.duration, undefined);
  assert.equal(malformed?.storyboardSpec, undefined);
  assert.deepEqual(malformed?.captionTracks, []);
  assert.equal(malformed?.heatmap, undefined);
  const valid = { videoId: 'video-a', title: 'Title', duration: 100, captionTracks: [{
    id: 'youtube:en', language: 'en', label: 'English', kind: 'subtitles', autoGenerated: false, baseUrl: 'url'
  }], markers: [{ startMillis: 0, title: 'Intro' }], heatmap: { source: 'markers', segments: [{ startMs: 0, durationMs: 100, intensity: 0.5 }] } };
  const normalized = readPublishedYoutubeSnapshot({ querySelector: () => ({ textContent: JSON.stringify(valid) }) as Element });
  assert.deepEqual(normalized?.captionTracks, valid.captionTracks);
  assert.deepEqual(normalized?.markers, valid.markers);
  assert.deepEqual(normalized?.heatmap, valid.heatmap);
});
