import { sanitizeContentTitle } from '../../media-features/content-title';
import { bilibiliPreviewFrame, bilibiliTimelineHeatmap, parseBilibiliCaptions, type BilibiliSnapshot } from '../../media-features/parsers/bilibili';
import { requestMediaProbe, requestPageFetch } from '../../media-features/probe';
import type { CaptionActivationResult, CaptionTrack, MediaCapabilities, MediaFeaturesAdapter, PreviewSource, TimelineHeatmap } from '../../media-features/types';

export class BilibiliAdapter implements MediaFeaturesAdapter {
  private snapshot: BilibiliSnapshot | null = null;
  private pending: Promise<void> | null = null;
  private generation = 0;

  private load(): Promise<void> {
    if (this.snapshot) return Promise.resolve();
    if (this.pending) return this.pending;
    const generation = this.generation;
    const pending = requestMediaProbe(3500, 'bilibili').then((snapshot) => {
      if (generation === this.generation) this.snapshot = snapshot.bilibili || null;
    }).finally(() => { if (this.pending === pending) this.pending = null; });
    this.pending = pending;
    return pending;
  }

  async probe(): Promise<MediaCapabilities> {
    await this.load();
    return { captions: Boolean(this.snapshot?.captionTracks.length), chapters: Boolean(this.snapshot?.chapters.length), previews: Boolean(this.snapshot?.storyboard) };
  }

  async listCaptionTracks(): Promise<CaptionTrack[]> {
    await this.load();
    return (this.snapshot?.captionTracks || []).map(({ id, language, label, autoGenerated }) => ({
      id, language, label, autoGenerated, kind: 'subtitles', source: 'bilibili', delivery: 'overlay'
    }));
  }

  async activateCaptionTrack(id: string | null): Promise<CaptionActivationResult> {
    if (id === null) return { status: 'off', delivery: 'none', cues: [] };
    await this.load();
    const track = this.snapshot?.captionTracks.find((t) => t.id === id);
    const generation = this.generation;
    const body = track ? await requestPageFetch(track.url) : null;
    const cues = body && generation === this.generation ? parseBilibiliCaptions(body) : [];
    return cues.length ? { status: 'active', delivery: 'overlay', cues } : { status: 'failed', delivery: 'none', cues: [] };
  }

  async getChapters() { await this.load(); return this.snapshot?.chapters || []; }
  getHeatmap(): TimelineHeatmap | null { return bilibiliTimelineHeatmap(this.snapshot); }
  async getPreviewSource(): Promise<PreviewSource> {
    await this.load();
    return this.snapshot?.storyboard ? { kind: 'sprite', provider: 'bilibili' } : { kind: 'none', reason: 'no-videoshot' };
  }
  getPreviewFrame(time: number) { return this.snapshot?.storyboard ? bilibiliPreviewFrame(this.snapshot.storyboard, time) : null; }
  mediaId() { return this.snapshot?.videoId || null; }
  getTitle() { return sanitizeContentTitle(this.snapshot?.title); }
  invalidate(): void { this.generation++; this.snapshot = null; this.pending = null; }
  async reload(): Promise<void> { this.invalidate(); await this.load(); }
  dispose(): void { this.invalidate(); }
}
