import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { bilibiliPreviewFrame, normalizeBilibiliSnapshot, parseBilibiliCaptions, parseBilibiliStoryboard } from '../../media-features/parsers/bilibili';
import { isAllowedMediaFetchUrl, classifyMediaFetchUrl } from '../../media-features/fetch-allowlist';
import { readBilibiliSnapshot } from './main';

// Field names and duplicate timestamps from the live videoshot response for BV1xx411c7mu.
const shot = {
  img_x_len: 10, img_y_len: 10, img_x_size: 160, img_y_size: 90,
  image: ['//i0.hdslb.com/bfs/videoshot/3635863.jpg'], index: [0, 0, 12, 21, 28, 40, 40, 46]
};

describe('Bilibili RTE', () => {
  it('uses sprite offsets with duplicate timestamps and clamps timeline edges', () => {
    const storyboard = parseBilibiliStoryboard(shot)!;
    assert.ok(storyboard);
    assert.equal(bilibiliPreviewFrame(storyboard, -1)?.image.x, 0);
    assert.equal(bilibiliPreviewFrame(storyboard, 40)?.image.x, 800);
    assert.equal(bilibiliPreviewFrame(storyboard, 999)?.time, 40);
    assert.equal(bilibiliPreviewFrame(storyboard, NaN), null);
    const sheets = parseBilibiliStoryboard({ ...shot, img_x_len: 2, img_y_len: 2,
      image: [...shot.image, '//i0.hdslb.com/bfs/videoshot/3635863-2.jpg'] })!;
    const frame = bilibiliPreviewFrame(sheets, 40)!;
    assert.equal(frame.image.url, 'https://i0.hdslb.com/bfs/videoshot/3635863-2.jpg');
    assert.equal(frame.image.x, 160);
    assert.equal(frame.image.y, 0);
  });

  it('rejects broken sprite dimensions, unordered indexes, and foreign image URLs', () => {
    for (const partial of [{ img_x_len: 0 }, { img_x_size: Infinity }, { index: [10, 3] },
      { image: ['https://evil.test/bfs/videoshot/1.jpg'] }, { image: ['javascript:alert(1)'] }]) {
      assert.equal(parseBilibiliStoryboard({ ...shot, ...partial }), null);
    }
  });

  it('parses subtitle JSON, sanitizes text, and drops invalid timings', () => {
    assert.deepEqual(parseBilibiliCaptions(JSON.stringify({ body: [
      { from: 2, to: 4, content: '<b>你好</b> &amp; hello' },
      { from: 0, to: 1, content: 'First<br>line' },
      { from: -1, to: 2, content: 'bad' }, { from: 3, to: 3, content: 'bad' },
      { from: 'NaN', to: 8, content: 'bad' }
    ] })), [{ start: 0, end: 1, text: 'First\nline' }, { start: 2, end: 4, text: '你好 & hello' }]);
    assert.deepEqual(parseBilibiliCaptions('<html>login</html>'), []);
    assert.deepEqual(parseBilibiliCaptions('{"body":{}}'), []);
  });

  it('imports only usable subtitle tracks and chapters, keyed to the current part', () => {
    const snapshot = normalizeBilibiliSnapshot('106:3635863', ' Video  title ', 318, {
      subtitle: { subtitles: [
        { id_str: '1', lan: 'ai-zh', lan_doc: '中文（自动生成）', subtitle_url: '//aisubtitle.hdslb.com/bfs/ai_subtitle/1.json' },
        { id: '2', lan: 'en', subtitle_url: 'https://evil.test/a.json' }
      ] }, view_points: [{ from: 10, to: 20, content: 'Part A' }, { from: -2, content: 'bad' }, { from: 320, content: 'past end' }]
    }, shot);
    assert.equal(snapshot.title, 'Video title');
    assert.equal(snapshot.captionTracks.length, 1);
    assert.equal(snapshot.captionTracks[0].autoGenerated, true);
    assert.equal(snapshot.captionTracks[0].id, 'bilibili:106:3635863:1');
    assert.deepEqual(snapshot.chapters.map(c => c.start), [10]);
    assert.ok(snapshot.storyboard);
  });

  it('restricts caption fetches to Bilibili subtitle JSON on the HTTPS CDN', () => {
    const url = 'https://aisubtitle.hdslb.com/bfs/ai_subtitle/track.json?auth_key=signed';
    assert.deepEqual(classifyMediaFetchUrl(url), { provider: 'bilibili', kind: 'caption-track', url });
    for (const url of ['http://i0.hdslb.com/bfs/subtitle/a.json', 'https://hdslb.com.evil.test/bfs/subtitle/a.json',
      'https://i0.hdslb.com/bfs/archive/a.json', 'https://user@i0.hdslb.com/bfs/subtitle/a.json']) {
      assert.equal(isAllowedMediaFetchUrl({ provider: 'bilibili', kind: 'caption-track', url }), false);
    }
  });

  it('isolates metadata by cid, discards late responses, and honors RTE-off', async () => {
    const oldWindow = globalThis.window;
    const oldDocument = globalThis.document;
    const oldFetch = globalThis.fetch;
    const state = { aid: 106, cid: 3635863, videoData: { title: 'First', duration: 318 } };
    let off = false;
    const resolvers: Array<(value: Response) => void> = [];
    let requests = 0;
    try {
      globalThis.window = { location: { hostname: 'www.bilibili.com' }, __INITIAL_STATE__: state } as any;
      globalThis.document = { documentElement: { hasAttribute: () => off }, querySelector: () => null } as any;
      globalThis.fetch = (async () => { requests++; return new Promise<Response>(resolve => { resolvers.push(resolve); }); }) as typeof fetch;
      const stale = readBilibiliSnapshot();
      state.cid = 42;
      for (const resolve of resolvers) resolve(new Response('{"code":0,"data":{}}'));
      assert.equal(await stale, null);
      off = true;
      assert.equal(await readBilibiliSnapshot(), null);
      off = false;
      globalThis.fetch = (async () => new Response(JSON.stringify({ code: 0, data: {} }))) as typeof fetch;
      const fresh = await readBilibiliSnapshot();
      assert.equal(fresh?.videoId, '106:42');
      assert.equal(requests, 2);
    } finally {
      globalThis.window = oldWindow; globalThis.document = oldDocument; globalThis.fetch = oldFetch;
    }
  });
});
