import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';
import type { Page } from 'playwright';
import { readStylesheet } from '../test-utils/styles';

const require = createRequire(import.meta.url);
const SRC = new URL('../', import.meta.url).pathname;
const CSS = readStylesheet(path.join(SRC, 'content.css'));
const esbuild = require('esbuild') as { buildSync(options: object): { outputFiles: Array<{ text: string }> } };
const BUNDLE = esbuild.buildSync({
  stdin: {
    contents: [
      "export { bootstrapPlayerRuntime } from './ui/player-runtime';",
      "export { setPlayerUiCss } from './ui/root';",
      "export { DisneyAdapter } from './media-features/disney-adapter';",
      "export { CompositeMediaAdapter } from './media-features/composite-adapter';"
    ].join('\n'),
    resolveDir: SRC, loader: 'ts'
  },
  bundle: true, write: false, format: 'iife', globalName: 'CaptionTest',
  platform: 'browser', target: 'es2022', logLevel: 'silent'
}).outputFiles[0].text;

/**
 * Holds a routed VTT response until the loading HUD and icon have been inspected.
 * @returns A pending promise and a callback that releases the response handler.
 */
function gate() {
  let release!: () => void;
  const promise = new Promise<void>(resolve => { release = resolve; });
  return { promise, release };
}

const FIXTURE = `<!doctype html><html><head><title>Caption loading fixture</title>
  <style>body { margin:0; background:#111; } video { width:960px; height:540px; }</style>
  </head><body><video id="player" title="Caption loading regression" muted playsinline></video>
  <script>
    const canvas = document.createElement('canvas');
    canvas.width = 1280; canvas.height = 720;
    const ctx = canvas.getContext('2d');
    const gradient = ctx.createLinearGradient(0, 0, 1280, 720);
    gradient.addColorStop(0, '#1c2634'); gradient.addColorStop(1, '#0b1018');
    ctx.fillStyle = gradient; ctx.fillRect(0, 0, 1280, 720);
    ctx.strokeStyle = '#29384a'; ctx.lineWidth = 2;
    for (let x = 0; x < 1280; x += 80) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, 720); ctx.stroke(); }
    for (let y = 0; y < 720; y += 80) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(1280, y); ctx.stroke(); }
    ctx.fillStyle = '#68788a'; ctx.font = '20px system-ui'; ctx.textAlign = 'center';
    ctx.fillText('LOCAL VIDEO FIXTURE', 640, 180);
    const video = document.querySelector('video');
    video.srcObject = canvas.captureStream(12);
    setInterval(() => { ctx.fillRect(0, 0, 1, 1); }, 100);
    video.play();
  </script></body></html>`;

/**
 * Starts the production player runtime with controlled extension settings and
 * enters theater mode on the fixture's playing video.
 * @param page Browser page containing the local video fixture.
 * @param host Host key used for the saved English caption preference.
 * @param saved Whether automatic caption restoration is enabled.
 * @returns When the theater controls have mounted.
 */
async function boot(page: Page, host: string, saved = true): Promise<void> {
  await page.evaluate(`window.chrome = { storage: {
    sync: {
      get: async () => ({ keepControlsVisible: true,
        captionPreferenceByHost: { [${JSON.stringify(host)}]: { enabled: ${saved}, language: 'en', autoGenerated: false } }
      }),
      set: async () => {}
    },
    onChanged: { addListener() {} }
  } };`);
  await page.addStyleTag({ content: CSS });
  await page.addScriptTag({ content: BUNDLE });
  await page.evaluate(`CaptionTest.setPlayerUiCss(${JSON.stringify(CSS)}); CaptionTest.bootstrapPlayerRuntime();`);
  await page.waitForFunction(() => document.querySelector('video')!.readyState >= 2);
  await page.keyboard.press('t');
  await page.locator('.theater-controls-wrapper').waitFor();
}

/**
 * Saves a regression screenshot when CAPTION_SCREENSHOT_DIR is configured.
 * @param page Production player page in the state being documented.
 * @param filename PNG filename relative to the configured output directory.
 * @returns When capture finishes, or immediately if screenshot output is disabled.
 */
async function screenshot(page: Page, filename: string): Promise<void> {
  const directory = process.env.CAPTION_SCREENSHOT_DIR;
  if (!directory) return;
  mkdirSync(directory, { recursive: true });
  await page.screenshot({ path: path.join(directory, filename) });
}

describe('caption loading browser regressions', () => {
  it('shows saved-caption loading in the real player, pulses both colors, handles reduced motion and failures', async t => {
    const { chromium } = await import('playwright');
    if (!existsSync(chromium.executablePath())) { t.skip('Chromium is not installed'); return; }
    const browser = await chromium.launch({ headless: true });
    const loading = gate();
    try {
      const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
      const errors: string[] = [];
      page.on('pageerror', error => errors.push(error.message));
      await page.route('http://captions.test/**', async route => {
        const pathname = new URL(route.request().url()).pathname;
        if (pathname === '/en.vtt') {
          await loading.promise;
          await route.fulfill({ contentType: 'text/vtt', body: 'WEBVTT\n\n00:00:00.000 --> 00:01:00.000\nSubtitles restored from the saved language.\n' });
        } else if (pathname === '/empty.vtt') {
          await route.fulfill({ contentType: 'text/vtt', body: 'WEBVTT\n' });
        } else {
          await route.fulfill({ contentType: 'text/html', body: FIXTURE.replace('</video>', '<track kind="subtitles" label="English" srclang="en" src="/en.vtt"><track kind="subtitles" label="Polish" srclang="pl" src="/empty.vtt"></video>') });
        }
      });
      await page.goto('http://captions.test/');
      await boot(page, 'captions.test');
      const button = page.locator('.cc-btn');
      const hud = page.locator('.theater-everywhere-caption-hud');
      await page.locator('.caption-hud-spinner').waitFor();
      assert.equal(await button.getAttribute('aria-busy'), 'true');
      assert.equal(await hud.innerText(), 'Loading subtitles...');
      const colors = await button.locator('svg').evaluate(async svg => {
        const animation = svg.getAnimations()[0];
        if (!animation) throw new Error('CC loading animation is missing');
        animation.pause();
        animation.currentTime = 0;
        const white = getComputedStyle(svg).color;
        animation.currentTime = 600;
        return { white, accent: getComputedStyle(svg).color };
      });
      assert.deepEqual(colors, { white: 'rgb(255, 255, 255)', accent: 'rgb(0, 117, 255)' });
      await screenshot(page, 'restore-loading-accent.png');
      await button.locator('svg').evaluate(svg => { svg.getAnimations()[0].currentTime = 0; });
      await screenshot(page, 'restore-loading-white.png');
      await page.emulateMedia({ reducedMotion: 'reduce' });
      assert.equal(await button.locator('svg').evaluate(svg => getComputedStyle(svg).animationName), 'none');
      assert.equal(await button.locator('svg').evaluate(svg => getComputedStyle(svg).color), 'rgb(0, 117, 255)');
      await page.emulateMedia({ reducedMotion: 'no-preference' });
      loading.release();
      await page.waitForFunction(() => document.querySelector('#theater-everywhere-ui')!.shadowRoot!.querySelector('.cc-btn')!.getAttribute('aria-busy') === 'false');
      assert.match(await hud.innerText(), /Subtitles on\s+English/);
      assert.equal(await page.locator('.cc-btn.active').count(), 1);
      assert.equal(await page.locator('.caption-hud-spinner').count(), 0);
      await screenshot(page, 'restore-complete.png');
      await button.click();
      await page.getByRole('button', { name: 'Polish', exact: true }).click();
      await page.waitForFunction(() => document.querySelector('#theater-everywhere-ui')!.shadowRoot!.querySelector('.theater-everywhere-caption-hud')?.textContent === "Couldn't load subtitles");
      assert.equal(await button.getAttribute('aria-busy'), 'false');
      assert.equal(await page.locator('.cc-btn.active, .cc-btn.loading').count(), 0);
      await screenshot(page, 'load-failed.png');
      assert.deepEqual(errors, []);
    } finally { loading.release(); await browser.close(); }
  });

  it('prepares Disney cue windows lazily, stays quiet within the loaded window and delegates through the composite', async t => {
    const { chromium } = await import('playwright');
    if (!existsSync(chromium.executablePath())) { t.skip('Chromium is not installed'); return; }
    const browser = await chromium.launch({ headless: true });
    try {
      const page = await browser.newPage();
      const mediaId = '00000000-0000-4000-8000-000000000001';
      const base = 'https://vod-akc-euwest1.media.dssott.com/ps01/';
      const requests: string[] = [];
      await page.route('https://www.disneyplus.com/**', route => route.fulfill({
        contentType: 'text/html',
        body: FIXTURE.replace('</body>', `<script id="theater-everywhere-disney-snapshot" type="application/json">${JSON.stringify({ mediaId, masterUrl: base + 'una-ctr-all-test.m3u8' })}</script></body>`)
      }));
      await page.route(base + '**', async route => {
        const pathname = new URL(route.request().url()).pathname;
        requests.push(pathname);
        const body = pathname.endsWith('una-ctr-all-test.m3u8')
          ? '#EXTM3U\n#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",LANGUAGE="en",FORCED=NO,URI="r/composite_en_NORMAL_test.m3u8"\n'
          : pathname.endsWith('composite_en_NORMAL_test.m3u8')
            ? '#EXTM3U\n' + Array.from({ length: 10 }, (_, index) => `#EXTINF:60,\ntext/${index}.vtt\n`).join('')
            : 'WEBVTT\n\n00:00:00.000 --> 00:00:05.000\nWindow caption.\n';
        await route.fulfill({ contentType: pathname.endsWith('.m3u8') ? 'application/vnd.apple.mpegurl' : 'text/vtt', headers: { 'access-control-allow-origin': '*' }, body });
      });
      await page.goto(`https://www.disneyplus.com/play/${mediaId}`);
      await page.addScriptTag({ content: BUNDLE });
      await page.evaluate(`(async () => {
        window.adapter = new CaptionTest.CompositeMediaAdapter([new CaptionTest.DisneyAdapter()]);
        const tracks = await adapter.listCaptionTracks();
        window.trackId = tracks[0].id;
        window.activation = await adapter.activateCaptionTrack(trackId);
      })()`);
      assert.equal(await page.evaluate('activation.status'), 'active');
      assert.equal(await page.evaluate('adapter.prepareCaptionCueRefresh(trackId, 20)'), null);
      const before = requests.length;
      assert.equal(await page.evaluate('window.request = adapter.prepareCaptionCueRefresh(trackId, 400); typeof request'), 'function');
      assert.equal(requests.length, before, 'preparation must not start a download');
      assert.equal(await page.evaluate('(async () => (await request()).status)()'), 'active');
      assert.ok(requests.length > before);
      assert.equal(await page.evaluate('adapter.prepareCaptionCueRefresh(trackId, 410)'), null);
      assert.equal(await page.evaluate('(async () => (await adapter.prepareCaptionCueRefresh(trackId, 580)()).status)()'), 'active');
      assert.equal(await page.evaluate('adapter.prepareCaptionCueRefresh(trackId, 595)'), null, 'the final cached segment must not trigger repeated loading');
      assert.equal(await page.evaluate('adapter.prepareCaptionCueRefresh("wrong-track", 500)'), null);
      await page.evaluate('adapter.invalidate()');
      assert.equal(await page.evaluate('adapter.prepareCaptionCueRefresh(trackId, 500)'), null);
      await page.evaluate('adapter.dispose()');
    } finally { await browser.close(); }
  });
});
