export const PLAYER_I18N_FALLBACKS: Record<string, string> = {
  keyboardShortcutsTitle: 'Keyboard Shortcuts',
  generalControlsTitle: 'General Controls',
  toggleTheaterMode: 'Toggle Theater Mode',
  exitTheaterMode: 'Exit Theater Mode',
  cycleSwitchVideo: 'Switch Video on Page',
  cycleVideoFit: 'Cycle Video Fit',
  onlyOneVideoHud: 'Feature unavailable. Video switching is only possible when there are more players on the page.',
  cycleIframeHud: 'Switching works only with HTML5 video',
  videoFitTooltip: 'Video Fit <kbd>$1</kbd>',
  videoFitContain: 'Fit',
  videoFitCover: 'Fill',
  videoFitFill: 'Stretch',
  showHideHelp: 'Show/Hide Help',
  playbackVolumeControlsTitle: 'Playback & Volume Controls',
  playPause: 'Play / Pause',
  seekBackward5: 'Seek Backward (5s)',
  seekForward5: 'Seek Forward (5s)',
  volumeUp5: 'Volume Up (5%)',
  volumeDown5: 'Volume Down (5%)',
  toggleMute: 'Toggle mute',
  frameFullscreenPipTitle: 'Frame, Fullscreen & PiP',
  frameStepBackward: 'Frame Step Backward',
  frameStepForward: 'Frame Step Forward',
  toggleFullscreen: 'Toggle Fullscreen',
  togglePictureInPicture: 'Toggle Picture-in-Picture',
  play: 'Play',
  pause: 'Pause',
  muteHud: 'Mute',
  unmuteHud: 'Unmute',
  pictureInPictureTooltip: 'Picture-in-Picture <kbd>$1</kbd>',
  exitFullscreen: 'Exit Fullscreen',
  fullscreenTooltip: 'Fullscreen <kbd>$1</kbd>',
  exitTheaterModeTooltip: 'Exit Theater Mode <kbd>$1</kbd> or <kbd>$2</kbd>',
  noSubtitlesAvailable: 'No subtitles available',
  disableSubtitles: 'Disable Subtitles',
  enableSubtitles: 'Enable Subtitles',
  toggleSubtitles: 'Toggle Subtitles',
  increaseSubtitleSize: 'Increase Subtitle Size',
  decreaseSubtitleSize: 'Decrease Subtitle Size',
  subtitlesTooltip: 'Subtitles <kbd>$1</kbd>',
  subtitlesOnHud: 'Subtitles on',
  subtitlesOnNamedHud: 'Subtitles on: $1',
  subtitlesOffHud: 'Subtitles off',
  subtitlesLoadingHud: 'Loading subtitles...',
  subtitlesLoadFailedHud: 'Couldn\'t load subtitles',
  noSubtitles: 'No subtitles',
  subtitlesOff: 'Off',
  liveBadge: 'LIVE',
  jumpToLive: 'Go to live',
  autoGeneratedTrack: '$1 (auto)',
  trackLabel: 'Track $1',
  subtitlesMenuTitle: 'Subtitles',
  subtitleOptions: 'Options',
  subtitleOptionsTitle: 'Subtitle options',
  subtitleTextColor: 'Text',
  subtitleSize: 'Size',
  subtitleDropShadow: 'Shadow',
  subtitleBackground: 'Background',
  subtitleOpacity: 'Opacity',
  subtitlePreviewSample: 'Sample caption',
  dialogDone: 'Done',
  switchVideoTooltip: 'Switch Video on Page <kbd>$1</kbd>',
  keyboardShortcutsTooltip: 'Keyboard Shortcuts <kbd>$1</kbd>',
  fiveSeconds: '5 seconds',
  '@@bidi_dir': 'ltr',
  '@@ui_locale': 'en'
};

export type UiDirection = 'ltr' | 'rtl';

export function t(messageName: string, substitutions?: string | string[]): string {
  try {
    if (typeof chrome !== 'undefined' && chrome.i18n && chrome.i18n.getMessage) {
      const message = chrome.i18n.getMessage(messageName, substitutions);
      if (message) {
        return message;
      }
    }
  } catch {
    // Content scripts can run in test pages without extension i18n.
  }

  let fallback = PLAYER_I18N_FALLBACKS[messageName] || messageName;
  const replacementValues = Array.isArray(substitutions)
    ? substitutions
    : substitutions === undefined
      ? []
      : [substitutions];

  replacementValues.forEach((value, index) => {
    fallback = fallback.replace(new RegExp(`\\$${index + 1}`, 'g'), () => value);
  });

  return fallback;
}

export function getUiDirection(): UiDirection {
  return t('@@bidi_dir') === 'rtl' ? 'rtl' : 'ltr';
}

export function applyUiDirection(element: HTMLElement): void {
  element.dir = getUiDirection();

  const language = t('@@ui_locale');
  if (language && !language.startsWith('@@')) {
    element.lang = language.replace('_', '-');
  }
}
