import { MAX_CAPTION_BYTES } from '../../platform/media-url-policy';
import { discoverParentOrigin } from '../../platform/parent-origin';
import { mediaProviderIntegrationEnabled } from '../../media-features/provider-flags';
import {
  parseTwitchGraphqlBody,
  TWITCH_CAPTIONS_ACK_EVENT,
  TWITCH_CAPTIONS_EVENT,
  TWITCH_HOST_CAPTION_ID
} from '../../media-features/parsers/twitch-page';
import { isTwitchHost } from '../hosts';

export function twitchIntegrationEnabled(): boolean {
  return mediaProviderIntegrationEnabled('twitch');
}

type TwitchHarvest = {
  videoId?: string;
  duration?: number;
  seekPreviewsURL?: string;
  moments: Array<{ startTime: number; endTime?: number; title: string }>;
  captions: Array<{ id: string; url: string; language: string; label: string; autoGenerated?: boolean }>;
};

let twitchHarvest: TwitchHarvest = { moments: [], captions: [] };
let twitchHarvestNotifyTimer = 0;

function twitchPageVideoId(href: string): string | null {
  try {
    const url = new URL(href, 'https://www.twitch.tv');
    if (!isTwitchHost(url.hostname)) return null;
    const parts = url.pathname.split('/').filter(Boolean);
    const videoIndex = parts.findIndex((part) => part === 'videos' || part === 'video');
    if (videoIndex >= 0 && parts[videoIndex + 1]) {
      const id = parts[videoIndex + 1].replace(/^v/i, '').replace(/[^\d].*$/, '');
      return id || null;
    }
    const queryVideo = url.searchParams.get('video') || url.searchParams.get('vod');
    if (!queryVideo) return null;
    const id = queryVideo.replace(/^v/i, '').replace(/[^\d].*$/, '');
    return id || null;
  } catch {
    return null;
  }
}

export function isAllowedTwitchStoryboardUrl(url: string): boolean {
  try {
    const parsed = new URL(url, window.location.href);
    if (parsed.protocol !== 'https:') return false;
    const host = parsed.hostname.replace(/^www\./i, '').toLowerCase();
    const hostOk = host === 'vod-secure.twitch.tv'
      || host === 'vod-storyboards.twitch.tv'
      || host === 'static-cdn.jtvnw.net'
      || /^d[a-z0-9]{6,}\.cloudfront\.net$/i.test(host);
    return hostOk && /\/storyboards\/[^/?#]*info\.json$/i.test(parsed.pathname);
  } catch {
    return false;
  }
}

function canonicalizeTwitchStoryboardUrl(url: string): string | null {
  try {
    const parsed = new URL(url, window.location.href);
    parsed.hash = '';
    if (!isAllowedTwitchStoryboardUrl(parsed.toString())) return null;
    return parsed.toString().slice(0, 2000);
  } catch {
    return null;
  }
}

function publishTwitchHarvest(): void {
  const payload = JSON.stringify({
    videoId: twitchHarvest.videoId || '',
    duration: twitchHarvest.duration || '',
    seekPreviewsURL: twitchHarvest.seekPreviewsURL || '',
    moments: twitchHarvest.moments,
    captions: twitchHarvest.captions
  });
  let node = document.getElementById('theater-everywhere-twitch-harvest');
  if (!node) {
    node = document.createElement('div');
    node.id = 'theater-everywhere-twitch-harvest';
    node.hidden = true;
    document.documentElement.appendChild(node);
  }
  if (node.textContent !== payload) node.textContent = payload;
}

function notifyTwitchHarvest(): void {
  publishTwitchHarvest();
  if (twitchHarvestNotifyTimer) return;
  twitchHarvestNotifyTimer = window.setTimeout(() => {
    twitchHarvestNotifyTimer = 0;
    window.dispatchEvent(new CustomEvent('theater-everywhere-twitch-harvest'));
  }, 80);
}

export function rememberTwitchStoryboardUrl(url: string): void {
  const canonical = canonicalizeTwitchStoryboardUrl(url);
  if (!canonical) return;
  const videoId = twitchPageVideoId(window.location.href);
  if (videoId && twitchHarvest.videoId && twitchHarvest.videoId !== videoId) {
    twitchHarvest = { videoId, moments: [], captions: [] };
  }
  const changed = twitchHarvest.seekPreviewsURL !== canonical;
  twitchHarvest.seekPreviewsURL = canonical;
  if (videoId) twitchHarvest.videoId = videoId;
  if (changed) notifyTwitchHarvest();
}

function addTwitchHarvestMoment(moment: { startTime: number; endTime?: number; title: string }): boolean {
  const key = `${moment.startTime}:${moment.title}`;
  if (twitchHarvest.moments.some((entry) => `${entry.startTime}:${entry.title}` === key)) return false;
  twitchHarvest.moments.push(moment);
  twitchHarvest.moments.sort((left, right) => left.startTime - right.startTime);
  return true;
}

type ReactFiber = {
  child?: ReactFiber | null;
  sibling?: ReactFiber | null;
  memoizedProps?: Record<string, unknown> | null;
  memoizedState?: unknown;
};

let twitchCaptionSetter: ((enabled: boolean) => void) | null = null;

function inspectTwitchCaptionBag(bag: unknown): { available?: boolean; setter?: (enabled: boolean) => void } {
  if (!bag || typeof bag !== 'object') return {};
  const record = bag as Record<string, unknown>;
  const captions = record.captions && typeof record.captions === 'object'
    ? record.captions as Record<string, unknown>
    : null;
  const setter = typeof record.setClosedCaptionsEnabled === 'function'
    ? record.setClosedCaptionsEnabled as (enabled: boolean) => void
    : undefined;
  const available = record.captionsAvailable === true || captions?.available === true
    ? true
    : record.captionsAvailable === false || captions?.available === false
      ? false
      : undefined;
  return { available, setter };
}

function readTwitchPlayerCaptionState(): { available: boolean; setter: ((enabled: boolean) => void) | null } {
  const root = document.querySelector('.persistent-player, .video-player');
  const fallback = Boolean(document.querySelector('button[aria-label^="Captions"]'));
  if (!(root instanceof HTMLElement)) {
    return { available: fallback, setter: twitchCaptionSetter };
  }
  const fiberKey = Object.keys(root).find((key) => key.startsWith('__reactFiber$'));
  if (!fiberKey) {
    return { available: fallback, setter: twitchCaptionSetter };
  }
  let available: boolean | undefined;
  let setter: ((enabled: boolean) => void) | null = twitchCaptionSetter;
  const walk = (fiber: ReactFiber | null | undefined, depth: number) => {
    if (!fiber || depth > 80) return;
    const bags: unknown[] = [fiber.memoizedProps, fiber.memoizedState];
    let hook: unknown = fiber.memoizedState;
    let hops = 0;
    while (hook && hops < 40) {
      bags.push(hook);
      const memo = (hook as { memoizedState?: unknown }).memoizedState;
      if (memo && typeof memo === 'object') bags.push(memo);
      hook = (hook as { next?: unknown }).next;
      hops += 1;
    }
    for (const bag of bags) {
      const found = inspectTwitchCaptionBag(bag);
      if (found.setter) setter = found.setter;
      if (found.available === true) available = true;
      else if (found.available === false && available !== true) available = false;
    }
    walk(fiber.child, depth + 1);
    walk(fiber.sibling, depth + 1);
  };
  try {
    walk((root as unknown as Record<string, ReactFiber>)[fiberKey], 0);
  } catch {
    // React internals are best-effort.
  }
  if (setter) twitchCaptionSetter = setter;
  return { available: available === true || fallback, setter };
}

function syncTwitchHostCaptionTrack(): boolean {
  const { available } = readTwitchPlayerCaptionState();
  const already = twitchHarvest.captions.some((entry) => entry.id === TWITCH_HOST_CAPTION_ID);
  if (available && !already) {
    twitchHarvest.captions.unshift({
      id: TWITCH_HOST_CAPTION_ID,
      url: '',
      language: '',
      label: 'Closed Captions'
    });
    return true;
  }
  if (!available && already) {
    twitchHarvest.captions = twitchHarvest.captions.filter((entry) => entry.id !== TWITCH_HOST_CAPTION_ID);
    return true;
  }
  return false;
}

function setTwitchClosedCaptionsEnabled(enabled: boolean): boolean {
  const state = readTwitchPlayerCaptionState();
  if (state.setter) {
    try {
      state.setter(enabled);
      return true;
    } catch {
      // Fall through to the player CC button.
    }
  }
  const button = document.querySelector('button[aria-label^="Captions"]');
  if (!(button instanceof HTMLElement)) return false;
  const pressed = button.getAttribute('aria-pressed');
  const label = button.getAttribute('aria-label')?.toLowerCase() || '';
  const current = pressed === 'true' || /\b(on|enabled)\b/.test(label)
    ? true
    : pressed === 'false' || /\b(off|disabled)\b/.test(label)
      ? false
      : null;
  if (current === null) return false;
  if (current === enabled) return true;
  button.click();
  return true;
}

export function harvestTwitchGqlBody(body: string): void {
  if (!body || body.length > MAX_CAPTION_BYTES) return;
  if (!/"seekPreviewsURL"|"positionMilliseconds"|"lengthSeconds"|"moments"|captions\.twitch\.tv/.test(body.slice(0, 200000))) return;
  const videoId = twitchPageVideoId(window.location.href);
  if (videoId && twitchHarvest.videoId && twitchHarvest.videoId !== videoId) {
    twitchHarvest = { videoId, moments: [], captions: [] };
  }
  if (videoId) twitchHarvest.videoId = videoId;
  let changed = false;
  const parsed = parseTwitchGraphqlBody(body, videoId);
  if (parsed.seekPreviewsURL) {
    const before = twitchHarvest.seekPreviewsURL;
    rememberTwitchStoryboardUrl(parsed.seekPreviewsURL);
    if (twitchHarvest.seekPreviewsURL !== before) changed = true;
  }
  if (parsed.duration && parsed.duration !== twitchHarvest.duration) {
    twitchHarvest.duration = parsed.duration;
    changed = true;
  }
  for (const moment of parsed.moments || []) {
    if (addTwitchHarvestMoment({ startTime: moment.start, endTime: moment.end, title: moment.title })) {
      changed = true;
    }
  }
  for (const caption of parsed.captions || []) {
    if (twitchHarvest.captions.some((entry) => entry.url === caption.url && entry.id === caption.id)) continue;
    twitchHarvest.captions.push(caption);
    changed = true;
  }
  if (syncTwitchHostCaptionTrack()) changed = true;
  publishTwitchHarvest();
  if (changed) notifyTwitchHarvest();
  postTwitchHarvestSnapshotToTop();
}

export function captureTwitchNetworkResponse(url: string, response: Response): void {
  if (!twitchIntegrationEnabled()) return;
  const finalUrl = (response && response.url) || url;
  if (response && response.ok && isAllowedTwitchStoryboardUrl(finalUrl)) {
    rememberTwitchStoryboardUrl(finalUrl);
  }
  if (!response || !response.ok) return;
  if (!/gql\.twitch\.tv/i.test(finalUrl) && !/gql\.twitch\.tv/i.test(url)) return;
  response.clone().text().then((text) => harvestTwitchGqlBody(text)).catch(() => {});
}

export function harvestTwitchResponseJson(url: string, data: unknown): void {
  if (!twitchIntegrationEnabled() || !/gql\.twitch\.tv/i.test(url)) return;
  harvestTwitchGqlBody(JSON.stringify(data));
}

export function harvestTwitchResponseText(url: string, text: string): void {
  if (!twitchIntegrationEnabled()) return;
  if (!(/gql\.twitch\.tv/i.test(url) || /"positionMilliseconds"|"seekPreviewsURL"/.test(text.slice(0, 4000)))) return;
  if (isTwitchHost(window.location.hostname) || /gql\.twitch\.tv/i.test(url)) {
    harvestTwitchGqlBody(text);
  }
}

export function harvestTwitchXhr(url: string, body: string | null, xhr: XMLHttpRequest): void {
  if (body && /gql\.twitch\.tv/i.test(url)) harvestTwitchGqlBody(body);
  if (isAllowedTwitchStoryboardUrl(url)) rememberTwitchStoryboardUrl(url);
  if (!body && /gql\.twitch\.tv/i.test(url) && xhr.responseType === 'blob' && xhr.response instanceof Blob) {
    xhr.response.text().then((text) => harvestTwitchGqlBody(text)).catch(() => {});
  }
}

export function readTwitchSnapshot(): Record<string, unknown> | null {
  try {
    if (!isTwitchHost(window.location.hostname)) return null;
    const videoId = twitchPageVideoId(window.location.href);
    if (!videoId) return { videoId: undefined };
    if (twitchHarvest.videoId && twitchHarvest.videoId !== videoId) {
      twitchHarvest = { videoId, moments: [], captions: [] };
    }
    const urls: string[] = [];
    const seenUrls = new Set<string>();
    const addUrl = (raw?: string | null) => {
      if (!raw) return;
      const canonical = canonicalizeTwitchStoryboardUrl(raw);
      if (!canonical || seenUrls.has(canonical)) return;
      seenUrls.add(canonical);
      urls.push(canonical);
    };
    addUrl(twitchHarvest.seekPreviewsURL);
    try {
      for (const entry of performance.getEntriesByType('resource')) {
        addUrl((entry as PerformanceResourceTiming).name);
      }
    } catch {
      // performance timeline may be unavailable.
    }
    const seekPreviewsURL = urls.find((url) => url.includes(videoId)) || urls[0];
    syncTwitchHostCaptionTrack();
    return {
      videoId,
      duration: twitchHarvest.duration,
      seekPreviewsURL,
      moments: [...twitchHarvest.moments],
      captionTracks: [...twitchHarvest.captions]
    };
  } catch {
    return null;
  }
}

export function twitchHarvestSnapshotMatchesPage(pageHref: string, snapshotVideoId?: string): boolean {
  const pageId = twitchPageVideoId(pageHref);
  if (!pageId) return true;
  return Boolean(snapshotVideoId) && snapshotVideoId === pageId;
}

function postTwitchHarvestSnapshotToTop(): void {
  if (window === window.top) return;
  const target = discoverParentOrigin();
  if (!target) return;
  try {
    if (!isTwitchHost(new URL(target).hostname)) return;
    window.top!.postMessage({
      type: 'theater-everywhere-twitch-harvest-snapshot',
      snapshot: {
        videoId: twitchHarvest.videoId,
        duration: twitchHarvest.duration,
        seekPreviewsURL: twitchHarvest.seekPreviewsURL,
        moments: twitchHarvest.moments
      }
    }, target);
  } catch {
    // Cross-origin parent frames cannot receive harvest copies.
  }
}

function applyTwitchHarvestSnapshot(snapshot: {
  videoId?: string;
  duration?: number;
  seekPreviewsURL?: string;
  moments?: TwitchHarvest['moments'];
}): void {
  let changed = false;
  if (snapshot.videoId && snapshot.videoId !== twitchHarvest.videoId) {
    twitchHarvest = { videoId: snapshot.videoId, moments: [], captions: [] };
    changed = true;
  }
  if (snapshot.duration && snapshot.duration !== twitchHarvest.duration) {
    twitchHarvest.duration = snapshot.duration;
    changed = true;
  }
  if (snapshot.seekPreviewsURL && snapshot.seekPreviewsURL !== twitchHarvest.seekPreviewsURL) {
    rememberTwitchStoryboardUrl(snapshot.seekPreviewsURL);
    changed = true;
  }
  for (const moment of snapshot.moments || []) {
    if (addTwitchHarvestMoment(moment)) changed = true;
  }
  publishTwitchHarvest();
  if (changed) notifyTwitchHarvest();
}

export function installTwitchMain(): void {
  window.addEventListener(TWITCH_CAPTIONS_EVENT, ((event: Event) => {
    const detail = (event as CustomEvent<{ enabled?: boolean; requestId?: string }>).detail;
    const enabled = Boolean(detail?.enabled);
    const applied = setTwitchClosedCaptionsEnabled(enabled);
    window.dispatchEvent(new CustomEvent(TWITCH_CAPTIONS_ACK_EVENT, {
      detail: { requestId: detail?.requestId || '', enabled, applied }
    }));
  }) as EventListener);
  window.addEventListener('message', (event: MessageEvent) => {
    if (window !== window.top) return;
    try {
      if (!isTwitchHost(new URL(event.origin).hostname)) return;
    } catch {
      return;
    }
    const fromChildFrame = Array.from(document.querySelectorAll('iframe')).some(
      (iframe) => iframe.contentWindow === event.source
    );
    if (!fromChildFrame) return;
    const data = event.data;
    if (data && data.type === 'theater-everywhere-twitch-harvest-snapshot' && data.snapshot && typeof data.snapshot === 'object') {
      if (!twitchHarvestSnapshotMatchesPage(window.location.href, data.snapshot.videoId)) return;
      applyTwitchHarvestSnapshot(data.snapshot);
    }
  });
  window.setTimeout(() => {
    if (syncTwitchHostCaptionTrack()) {
      publishTwitchHarvest();
      notifyTwitchHarvest();
    }
  }, 1500);
}
