import { sanitizeContentTitle } from '../content-title';
import { sanitizeCaptionCueText } from '../sanitize';
import type { CaptionCue, Chapter, PreviewFrame } from '../types';
import { isAllowedMediaFetchUrl } from '../fetch-allowlist';

export type BilibiliCaption = {
  id: string;
  language: string;
  label: string;
  url: string;
  autoGenerated: boolean;
};

export type BilibiliStoryboard = {
  images: string[];
  times: number[];
  columns: number;
  rows: number;
  width: number;
  height: number;
};

export type BilibiliSnapshot = {
  videoId: string;
  title?: string;
  duration?: number;
  captionTracks: BilibiliCaption[];
  chapters: Chapter[];
  storyboard: BilibiliStoryboard | null;
};

function record(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

export function bilibiliAssetUrl(value: unknown): string | null {
  if (typeof value !== 'string' || value.length > 2000) return null;
  try {
    const url = new URL(value, 'https://www.bilibili.com');
    if (url.protocol !== 'https:' || url.username || url.password || url.port) return null;
    return url.href;
  } catch {
    return null;
  }
}

export function parseBilibiliStoryboard(raw: unknown): BilibiliStoryboard | null {
  const data = record(raw);
  const columns = Number(data.img_x_len);
  const rows = Number(data.img_y_len);
  const width = Number(data.img_x_size);
  const height = Number(data.img_y_size);
  if (![columns, rows, width, height].every((n) => Number.isInteger(n) && n > 0 && n <= 2048)) return null;
  if (columns * width > 32768 || rows * height > 32768) return null;
  if (!Array.isArray(data.image) || !Array.isArray(data.index)) return null;
  const images = data.image.slice(0, 200).map(bilibiliAssetUrl);
  if (!images.length || images.some((value) => !value || !isStoryboardImage(value))) return null;
  // The official player's getIndex selects interval n and displays tile n - 1:
  // index[0] is a sentinel and the final index is the end boundary, not a tile.
  // Preserve duplicate timestamps inside those boundaries.
  const times = data.index.slice(1, -1).slice(0, Math.min(20000, images.length * columns * rows)).map(Number);
  if (!times.length || times.some((n, i) => !Number.isFinite(n) || n < 0 || (i > 0 && n < times[i - 1]))) return null;
  return { images: images as string[], times, columns, rows, width, height };
}

function isStoryboardImage(value: string): boolean {
  const url = new URL(value);
  return (url.hostname.endsWith('.hdslb.com') || url.hostname.endsWith('.biliimg.com'))
    && /^\/bfs\/videoshot\/.+\.(?:jpe?g|png|webp)$/i.test(url.pathname);
}

export function bilibiliPreviewFrame(storyboard: BilibiliStoryboard, time: number): PreviewFrame | null {
  if (!Number.isFinite(time)) return null;
  let index = 0;
  for (let i = 1; i < storyboard.times.length && storyboard.times[i] <= Math.max(0, time); i++) index = i;
  const perSheet = storyboard.columns * storyboard.rows;
  const tile = index % perSheet;
  const url = storyboard.images[Math.floor(index / perSheet)];
  if (!url) return null;
  return {
    time: storyboard.times[index], width: storyboard.width, height: storyboard.height,
    image: {
      kind: 'sprite', url,
      x: (tile % storyboard.columns) * storyboard.width,
      y: Math.floor(tile / storyboard.columns) * storyboard.height,
      tileWidth: storyboard.width, tileHeight: storyboard.height,
      sheetWidth: storyboard.width * storyboard.columns, sheetHeight: storyboard.height * storyboard.rows
    }
  };
}

export function parseBilibiliCaptions(body: string): CaptionCue[] {
  if (body.length > 2 * 1024 * 1024) return [];
  try {
    const data = record(JSON.parse(body));
    if (!Array.isArray(data.body)) return [];
    return data.body.slice(0, 20000).flatMap((raw): CaptionCue[] => {
      const row = record(raw);
      const start = Number(row.from);
      const end = Number(row.to);
      const text = typeof row.content === 'string' ? sanitizeCaptionCueText(row.content).slice(0, 4000) : '';
      return Number.isFinite(start) && Number.isFinite(end) && start >= 0 && end > start && text
        ? [{ start, end, text }] : [];
    }).sort((a, b) => a.start - b.start);
  } catch {
    return [];
  }
}

export function normalizeBilibiliSnapshot(
  videoId: string, title: unknown, duration: number, playerInfo: unknown, videoshot: unknown
): BilibiliSnapshot {
  const data = record(playerInfo);
  const tracks = record(data.subtitle).subtitles;
  const captionTracks = (Array.isArray(tracks) ? tracks : []).slice(0, 80).flatMap((raw, index): BilibiliCaption[] => {
    const track = record(raw);
    const url = bilibiliAssetUrl(track.subtitle_url);
    if (!url || !isAllowedMediaFetchUrl({ provider: 'bilibili', kind: 'caption-track', url })) return [];
    const language = typeof track.lan === 'string' ? track.lan.slice(0, 40) : '';
    return [{
      id: `bilibili:${videoId}:${String(track.id_str || track.id || index).slice(0, 80)}`,
      language, label: sanitizeContentTitle(track.lan_doc) || language,
      url, autoGenerated: language.startsWith('ai-') || Number(track.ai_type) > 0
    }];
  });
  const chapters = (Array.isArray(data.view_points) ? data.view_points : []).slice(0, 200).flatMap((raw): Chapter[] => {
    const row = record(raw);
    const start = Number(row.from);
    const end = Number(row.to);
    const title = sanitizeContentTitle(row.content);
    if (!title || !Number.isFinite(start) || start < 0 || (duration > 0 && start >= duration)) return [];
    return [{ start, ...(Number.isFinite(end) && end > start ? { end } : {}), title, source: 'bilibili', confidence: 'high' }];
  }).sort((a, b) => a.start - b.start);
  return {
    videoId, title: sanitizeContentTitle(title) || undefined,
    duration: Number.isFinite(duration) && duration > 0 ? duration : undefined,
    captionTracks, chapters, storyboard: parseBilibiliStoryboard(videoshot)
  };
}
