export type PatreonPageCaption = {
  id: string;
  url: string;
  language: string;
  label: string;
  autoGenerated?: boolean;
};

export type PatreonCaptionMetaHint = {
  language?: string;
  label?: string;
  autoGenerated?: boolean;
};

export type PatreonPageAssets = {
  playbackId: string;
  storyboardVttUrl?: string;
  storyboardJsonUrl?: string;
  captions: PatreonPageCaption[];
};

function decodePatreonHtml(html: string): string {
  return html
    .replace(/\\u002f/gi, '/')
    .replace(/\\u0026/gi, '&')
    .replace(/\\u003d/gi, '=')
    .replace(/\\\//g, '/');
}

function clipUrl(url: string): string {
  return url.replace(/[\\]+$/, '').slice(0, 2000);
}

function ensureAsset(map: Map<string, PatreonPageAssets>, playbackId: string): PatreonPageAssets {
  let asset = map.get(playbackId);
  if (!asset) {
    asset = { playbackId, captions: [] };
    map.set(playbackId, asset);
  }
  return asset;
}

export function muxCaptionPath(url: string): string | null {
  try {
    const parsed = new URL(url);
    if (parsed.hostname.replace(/^www\./i, '').toLowerCase() !== 'stream.mux.com') return null;
    return /\/[^/]+\/text\/[^/]+\.vtt$/i.test(parsed.pathname) ? parsed.pathname.toLowerCase() : null;
  } catch {
    return null;
  }
}

export function captionLooksAutoGenerated(label: string): boolean {
  return /auto[- ]generated|\(auto\)/i.test(label);
}

function isGenericCaptionLabel(label: string): boolean {
  const value = label.trim().toLowerCase();
  return !value || value === 'captions' || value === 'subtitles';
}

function captionMetaScore(track: PatreonPageCaption): number {
  let score = 0;
  if (track.language) score += 2;
  if (!isGenericCaptionLabel(track.label || '')) score += 2;
  if (track.autoGenerated || captionLooksAutoGenerated(track.label || '')) score += 1;
  return score;
}

function withCaptionMeta(track: PatreonPageCaption, meta: PatreonCaptionMetaHint): PatreonPageCaption {
  const metaLabel = (meta.label || '').trim();
  const label = !isGenericCaptionLabel(metaLabel)
    ? metaLabel.slice(0, 80)
    : track.label;
  const language = (track.language || meta.language || '').slice(0, 16);
  const autoGenerated = Boolean(
    track.autoGenerated
    || meta.autoGenerated
    || captionLooksAutoGenerated(label)
    || captionLooksAutoGenerated(metaLabel)
  );
  return {
    ...track,
    language,
    label: label || track.label || 'Captions',
    autoGenerated
  };
}

export function parsePatreonPageAssets(html: string): PatreonPageAssets[] {
  const text = decodePatreonHtml(html);
  const byId = new Map<string, PatreonPageAssets>();

  for (const match of text.matchAll(
    /https:\/\/image\.mux\.com\/([A-Za-z0-9_-]+)\/storyboard\.(vtt|json)(\?[^"'\\\s<>]*)?/gi
  )) {
    const asset = ensureAsset(byId, match[1]);
    const url = clipUrl(match[0]);
    if (match[2].toLowerCase() === 'json') {
      if (!asset.storyboardJsonUrl) asset.storyboardJsonUrl = url;
    } else if (!asset.storyboardVttUrl) {
      asset.storyboardVttUrl = url;
    }
  }

  for (const match of text.matchAll(
    /https:\/\/stream\.mux\.com\/([A-Za-z0-9_-]+)\/text\/([A-Za-z0-9_-]+)\.vtt(\?[^"'\\\s<>]*)?/gi
  )) {
    const asset = ensureAsset(byId, match[1]);
    const url = clipUrl(match[0]);
    const path = muxCaptionPath(url);
    if (asset.captions.some((caption) => caption.url === url || muxCaptionPath(caption.url) === path)) {
      continue;
    }
    asset.captions.push({
      id: `patreon:${match[1]}:${match[2]}`.slice(0, 160),
      url,
      language: '',
      label: 'Captions'
    });
  }

  return [...byId.values()];
}

export function pickPatreonPageAssets(
  assets: PatreonPageAssets[],
  playbackId?: string
): PatreonPageAssets | null {
  if (playbackId) {
    const match = assets.find((asset) => asset.playbackId === playbackId);
    if (match) return match;
  }
  return assets.find((asset) => asset.storyboardVttUrl || asset.storyboardJsonUrl || asset.captions.length > 0)
    || null;
}

export function mergePatreonCaptionTracks(
  ...lists: Array<PatreonPageCaption[] | undefined>
): PatreonPageCaption[] {
  const merged: PatreonPageCaption[] = [];
  const seen = new Map<string, number>();
  for (const list of lists) {
    if (!list) continue;
    for (const track of list) {
      const path = muxCaptionPath(track.url);
      const key = path || track.url || track.id;
      if (!key) continue;
      const existingIndex = seen.get(key);
      if (existingIndex === undefined) {
        seen.set(key, merged.length);
        merged.push(track);
        continue;
      }
      if (captionMetaScore(track) > captionMetaScore(merged[existingIndex])) {
        merged[existingIndex] = withCaptionMeta(track, merged[existingIndex]);
        if (track.url) merged[existingIndex].url = track.url;
      } else {
        merged[existingIndex] = withCaptionMeta(merged[existingIndex], track);
      }
    }
  }
  return merged;
}

export function applyPatreonCaptionMeta(
  tracks: PatreonPageCaption[],
  meta: PatreonCaptionMetaHint[]
): PatreonPageCaption[] {
  const usable = meta.filter((item) => item.language || (item.label && !isGenericCaptionLabel(item.label)));
  if (tracks.length === 0 || usable.length === 0) return tracks;
  if (tracks.length === 1) {
    const best = usable.reduce((winner, item) => (
      captionMetaScore({
        id: '',
        url: '',
        language: item.language || '',
        label: item.label || '',
        autoGenerated: item.autoGenerated
      }) > captionMetaScore({
        id: '',
        url: '',
        language: winner.language || '',
        label: winner.label || '',
        autoGenerated: winner.autoGenerated
      }) ? item : winner
    ));
    return [withCaptionMeta(tracks[0], best)];
  }
  return tracks.map((track) => {
    const language = (track.language || '').toLowerCase();
    const byLang = language
      ? usable.find((item) => (item.language || '').toLowerCase().split('-')[0] === language.split('-')[0])
      : undefined;
    if (byLang) return withCaptionMeta(track, byLang);
    if (isGenericCaptionLabel(track.label) && usable.length === 1) return withCaptionMeta(track, usable[0]);
    return track;
  });
}
