import { isSafeTwitchStoryboardJsonUrl } from './twitch-storyboard';
import { isTwitchHost } from '../../providers/hosts';

export { isTwitchHost };

export type TwitchPageMoment = {
  start: number;
  end?: number;
  title: string;
};

export type TwitchPageCaption = {
  id: string;
  url: string;
  language: string;
  label: string;
  autoGenerated?: boolean;
  delivery?: 'overlay' | 'host';
};

export const TWITCH_HOST_CAPTION_ID = 'twitch:host-cc';
export const TWITCH_CAPTIONS_EVENT = 'theater-everywhere-twitch-captions';

export type TwitchPageAssets = {
  videoId: string | null;
  duration?: number;
  seekPreviewsURL?: string;
  moments: TwitchPageMoment[];
  captions: TwitchPageCaption[];
};

function decodeTwitchHtml(html: string): string {
  return html
    .replace(/\\u002f/gi, '/')
    .replace(/\\u0026/gi, '&')
    .replace(/\\u003d/gi, '=')
    .replace(/\\u0022/gi, '"')
    .replace(/\\\//g, '/');
}

function unescapeJsonString(value: string): string {
  return value
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, hex: string) => String.fromCharCode(parseInt(hex, 16)))
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\');
}

function clipUrl(url: string): string {
  return url.replace(/[\\]+$/, '').slice(0, 2000);
}

export function twitchPageVideoId(href: string): string | null {
  try {
    const url = new URL(href, 'https://www.twitch.tv');
    if (!isTwitchHost(url.hostname)) return null;
    const parts = url.pathname.split('/').filter(Boolean);
    const videoIndex = parts.findIndex((part) => part === 'videos' || part === 'video');
    if (videoIndex >= 0 && parts[videoIndex + 1]) {
      const id = parts[videoIndex + 1].replace(/^v/i, '').replace(/[^\d].*$/, '');
      return id || null;
    }
    const queryVideo = url.searchParams.get('video') || url.searchParams.get('vod');
    if (!queryVideo) return null;
    const id = queryVideo.replace(/^v/i, '').replace(/[^\d].*$/, '');
    return id || null;
  } catch {
    return null;
  }
}

export function isSafeTwitchCaptionUrl(url: string, baseUrl?: string): boolean {
  try {
    const parsed = new URL(url, baseUrl || 'https://www.twitch.tv');
    if (parsed.protocol !== 'https:') return false;
    const host = parsed.hostname.replace(/^www\./i, '').toLowerCase();
    if (host !== 'captions.twitch.tv' && !host.endsWith('.captions.twitch.tv')) return false;
    return /\.vtt$/i.test(parsed.pathname);
  } catch {
    return false;
  }
}

function collectSeekPreviewsUrls(text: string): string[] {
  const urls: string[] = [];
  const seen = new Set<string>();
  const add = (raw: string) => {
    const url = clipUrl(raw);
    const canonical = canonicalizeTwitchStoryboardUrl(url);
    if (!canonical || seen.has(canonical)) return;
    seen.add(canonical);
    urls.push(canonical);
  };
  for (const match of text.matchAll(/"seekPreviewsURL"\s*:\s*"([^"]+)"/gi)) {
    add(match[1]);
  }
  for (const match of text.matchAll(
    /https:\/\/(?:vod-secure\.twitch\.tv|vod-storyboards\.twitch\.tv|static-cdn\.jtvnw\.net|d[a-z0-9]+\.cloudfront\.net)\/[^"'\\\s<>]*\/storyboards\/[^"'\\\s<>]*info\.json(?:\?[^"'\\\s<>]*)?/gi
  )) {
    add(match[0]);
  }
  return urls;
}

export function canonicalizeTwitchStoryboardUrl(url: string): string | null {
  try {
    const parsed = new URL(url);
    parsed.hash = '';
    if (!isSafeTwitchStoryboardJsonUrl(parsed.toString())) return null;
    return parsed.toString();
  } catch {
    return null;
  }
}

export type TwitchVodLocation = {
  assetId: string;
  distributionId?: string;
};

export function twitchStoryboardUrlCandidates(location: TwitchVodLocation, videoId: string): string[] {
  if (!/^[A-Za-z0-9_-]+$/.test(location.assetId) || !/^\d+$/.test(videoId)) return [];
  const file = `${videoId}-info.json`;
  const urls: string[] = [];
  if (location.distributionId && /^d[a-z0-9]{6,}$/i.test(location.distributionId)) {
    urls.push(`https://${location.distributionId.toLowerCase()}.cloudfront.net/${location.assetId}/storyboards/${file}`);
  }
  urls.push(`https://vod-secure.twitch.tv/${location.assetId}/storyboards/${file}`);
  urls.push(`https://vod-storyboards.twitch.tv/${location.assetId}/storyboards/${file}`);
  return urls;
}

export function twitchStoryboardUrlForAsset(vodAssetId: string, videoId: string): string | null {
  return twitchStoryboardUrlCandidates({ assetId: vodAssetId }, videoId)[0] || null;
}

export function collectTwitchVodLocations(html: string): TwitchVodLocation[] {
  const text = decodeTwitchHtml(html);
  const locations: TwitchVodLocation[] = [];
  const seen = new Set<string>();
  const add = (assetId: string, distributionId?: string) => {
    if (!assetId || !/^[A-Za-z0-9_-]{8,}$/.test(assetId)) return;
    const dist = distributionId && /^d[a-z0-9]{6,}$/i.test(distributionId)
      ? distributionId.toLowerCase()
      : undefined;
    const key = `${dist || ''}:${assetId}`;
    if (seen.has(key)) return;
    seen.add(key);
    locations.push({ assetId, distributionId: dist });
  };
  for (const match of text.matchAll(/static-cdn\.jtvnw\.net\/cf_vods\/(d[a-z0-9]{6,})\/([A-Za-z0-9_-]+)\//gi)) {
    add(match[2], match[1]);
  }
  for (const match of text.matchAll(/https:\/\/(d[a-z0-9]{6,})\.cloudfront\.net\/([A-Za-z0-9_-]+)\//gi)) {
    add(match[2], match[1]);
  }
  for (const match of text.matchAll(/(?:vod-secure\.twitch\.tv|vod-storyboards\.twitch\.tv)\/([A-Za-z0-9_-]+)\//gi)) {
    add(match[1]);
  }
  return locations.slice(0, 8);
}

export function collectTwitchVodAssetIds(html: string): string[] {
  const ids: string[] = [];
  const seen = new Set<string>();
  for (const location of collectTwitchVodLocations(html)) {
    if (seen.has(location.assetId)) continue;
    seen.add(location.assetId);
    ids.push(location.assetId);
  }
  return ids;
}

export function collectTwitchStoryboardUrls(html: string, videoId: string, extra: string[] = []): string[] {
  const text = decodeTwitchHtml(html);
  const urls: string[] = [];
  const seen = new Set<string>();
  const add = (url?: string | null) => {
    if (!url) return;
    const canonical = canonicalizeTwitchStoryboardUrl(url);
    if (!canonical || seen.has(canonical)) return;
    seen.add(canonical);
    urls.push(canonical);
  };
  for (const url of extra) add(url);
  for (const url of collectSeekPreviewsUrls(text)) add(url);
  for (const location of collectTwitchVodLocations(text)) {
    for (const url of twitchStoryboardUrlCandidates(location, videoId)) add(url);
  }
  const withId = urls.filter((url) => url.includes(videoId));
  return (withId.length > 0 ? withId : urls).slice(0, 8);
}

function pickSeekPreviewsUrl(urls: string[], videoId: string | null): string | undefined {
  if (urls.length === 0) return undefined;
  if (videoId) {
    const match = urls.find((url) => url.includes(videoId));
    if (match) return match;
  }
  return urls[0];
}

function momentTitleFromNode(node: Record<string, unknown>): string {
  const details = node.details && typeof node.details === 'object'
    ? node.details as Record<string, unknown>
    : null;
  const game = details?.game && typeof details.game === 'object'
    ? details.game as Record<string, unknown>
    : null;
  const title = [
    node.description,
    node.subDescription,
    node.name,
    node.title,
    game?.displayName,
    game?.name
  ].find((value) => typeof value === 'string' && value.trim());
  return typeof title === 'string' ? title.trim() : '';
}

function momentsFromNode(node: Record<string, unknown>): TwitchPageMoment[] {
  let source: Record<string, unknown>[] = [];
  if (Array.isArray(node.moments)) {
    source = node.moments as Record<string, unknown>[];
  } else if (Array.isArray((node.moments as { edges?: unknown[] } | undefined)?.edges)) {
    source = ((node.moments as { edges: Array<{ node?: Record<string, unknown> }> }).edges
      .map((edge) => edge?.node)
      .filter(Boolean) as Record<string, unknown>[]);
  }
  if (source.length === 0 && node.positionMilliseconds != null) {
    source = [node];
  }
  const moments: TwitchPageMoment[] = [];
  const seen = new Set<string>();
  for (const moment of source) {
    if (!moment || typeof moment !== 'object') continue;
    const item = moment as Record<string, unknown>;
    const startMs = Number(item.positionMilliseconds);
    const title = momentTitleFromNode(item);
    if (!Number.isFinite(startMs) || startMs < 0 || !title) continue;
    const key = `${startMs}:${title}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const durationMs = Number(item.durationMilliseconds);
    moments.push({
      start: startMs / 1000,
      end: Number.isFinite(durationMs) ? startMs / 1000 + durationMs / 1000 : undefined,
      title: title.slice(0, 120)
    });
  }
  return moments;
}

export function extractTwitchPayloadFromJson(raw: unknown, videoId?: string | null): Partial<TwitchPageAssets> {
  const videos: Array<{
    id: string;
    seekPreviewsURL?: string;
    duration?: number;
    moments: TwitchPageMoment[];
  }> = [];
  let budget = 4000;

  const walk = (node: unknown, depth: number) => {
    if (budget <= 0 || node == null || depth > 12) return;
    budget -= 1;
    if (Array.isArray(node)) {
      for (const item of node) walk(item, depth + 1);
      return;
    }
    if (typeof node !== 'object') return;
    const record = node as Record<string, unknown>;
    const hasVideoFields = typeof record.seekPreviewsURL === 'string'
      || record.moments != null
      || record.lengthSeconds != null
      || record.positionMilliseconds != null;
    if (hasVideoFields) {
      const id = record.id != null ? String(record.id).replace(/^v/i, '') : '';
      const length = Number(record.lengthSeconds ?? record.length);
      videos.push({
        id,
        seekPreviewsURL: typeof record.seekPreviewsURL === 'string'
          ? canonicalizeTwitchStoryboardUrl(record.seekPreviewsURL) || undefined
          : undefined,
        duration: Number.isFinite(length) && length > 0 ? length : undefined,
        moments: momentsFromNode(record)
      });
    }
    for (const value of Object.values(record)) walk(value, depth + 1);
  };

  walk(raw, 0);
  const matching = videoId
    ? videos.filter((video) => video.id === videoId)
    : videos;
  if (videoId && matching.length === 0) {
    return { videoId, moments: [], captions: [] };
  }
  const pool = matching.length > 0 ? matching : videos;
  if (pool.length === 0) return { moments: [], captions: [] };
  const moments: TwitchPageMoment[] = [];
  const seen = new Set<string>();
  for (const video of pool) {
    for (const moment of video.moments) {
      const key = `${moment.start}:${moment.title}`;
      if (seen.has(key)) continue;
      seen.add(key);
      moments.push(moment);
    }
  }
  moments.sort((left, right) => left.start - right.start);
  return {
    videoId: pool.find((video) => video.id)?.id || videoId || null,
    duration: pool.find((video) => video.duration)?.duration,
    seekPreviewsURL: pool.find((video) => video.seekPreviewsURL)?.seekPreviewsURL,
    moments: moments.slice(0, 80),
    captions: []
  };
}

export function parseTwitchGraphqlBody(body: string, videoId?: string | null): Partial<TwitchPageAssets> {
  const trimmed = body.trim();
  if (!trimmed || (!trimmed.startsWith('{') && !trimmed.startsWith('['))) {
    return { moments: [], captions: [] };
  }
  if (!/"seekPreviewsURL"|"positionMilliseconds"|"lengthSeconds"|"moments"|captions\.twitch\.tv/.test(trimmed.slice(0, 200000))) {
    return { moments: [], captions: [] };
  }
  try {
    const parsed = extractTwitchPayloadFromJson(JSON.parse(trimmed), videoId);
    const captions = parseTwitchCaptionTracks(trimmed, videoId);
    return captions.length > 0 ? { ...parsed, captions } : parsed;
  } catch {
    return { moments: [], captions: [] };
  }
}

const TWITCH_VIDEO_FIELD = '(?:broadcastType|lengthSeconds|seekPreviewsURL|moments|previewThumbnailURL|animatedPreviewURL)';

function slicesForVideoId(text: string, videoId: string): string[] {
  if (!/^\d+$/.test(videoId)) return [];
  const idRe = new RegExp(`"id"\\s*:\\s*"${videoId}"|"id"\\s*:\\s*${videoId}(?!\\d)`, 'g');
  const nextVideoRe = new RegExp(`"id"\\s*:\\s*"?(?!${videoId})\\d+"?\\s*,\\s*"${TWITCH_VIDEO_FIELD}"`);
  const slices: string[] = [];
  for (const match of text.matchAll(idRe)) {
    const rest = text.slice(match.index ?? 0);
    const next = rest.search(nextVideoRe);
    slices.push(rest.slice(0, next >= 0 ? next : Math.min(rest.length, 120_000)));
  }
  return slices;
}

export function parseTwitchMoments(html: string, videoId?: string | null): TwitchPageMoment[] {
  const text = decodeTwitchHtml(html);
  if (!videoId) return [];
  const moments: TwitchPageMoment[] = [];
  const seen = new Set<string>();
  const addFrom = (source: string) => {
    for (const match of source.matchAll(/"positionMilliseconds"\s*:\s*(\d+)/g)) {
      const startMs = Number(match[1]);
      if (!Number.isFinite(startMs) || startMs < 0 || match.index == null) continue;
      const after = source.slice(match.index, match.index + 220);
      const before = source.slice(Math.max(0, match.index - 220), match.index);
      const durationMatch = after.match(/"durationMilliseconds"\s*:\s*(\d+)/)
        || before.match(/"durationMilliseconds"\s*:\s*(\d+)/);
      const descMatch = after.match(/"description"\s*:\s*"((?:\\.|[^"\\])*)"/)
        || before.match(/"description"\s*:\s*"((?:\\.|[^"\\])*)"/);
      const title = descMatch ? unescapeJsonString(descMatch[1]).trim() : '';
      if (!title) continue;
      const start = startMs / 1000;
      const durationMs = durationMatch ? Number(durationMatch[1]) : NaN;
      const key = `${start}:${title}`;
      if (seen.has(key)) continue;
      seen.add(key);
      moments.push({
        start,
        end: Number.isFinite(durationMs) ? start + durationMs / 1000 : undefined,
        title: title.slice(0, 120)
      });
    }
  };
  for (const slice of slicesForVideoId(text, videoId)) addFrom(slice);
  moments.sort((left, right) => left.start - right.start);
  return moments.slice(0, 80);
}

export function parseTwitchCaptionTracks(html: string, videoId?: string | null): TwitchPageCaption[] {
  const text = decodeTwitchHtml(html);
  const captions: TwitchPageCaption[] = [];
  const seen = new Set<string>();
  for (const match of text.matchAll(
    /https:\/\/(?:[\w-]+\.)?captions\.twitch\.tv\/[^\s"'<>\\]+?\.vtt(?:\?[^"'\\\s<>]*)?/gi
  )) {
    const url = clipUrl(match[0]);
    if (!isSafeTwitchCaptionUrl(url) || seen.has(url)) continue;
    if (videoId && !url.includes(videoId)) continue;
    seen.add(url);
    const languageMatch = url.match(/[?&]language=([A-Za-z]{2,8}(?:-[A-Za-z0-9]+)?)(?:&|$)/i)
      || url.match(/\/([A-Za-z]{2,8}(?:-[A-Za-z0-9]+)?)\/[^/]+\.vtt/i);
    const language = (languageMatch?.[1] || '').slice(0, 16);
    captions.push({
      id: `twitch:${language || captions.length}:${url.slice(-48)}`.slice(0, 160),
      url,
      language,
      label: language || 'Captions'
    });
  }
  return captions.slice(0, 20);
}

function parseTwitchDuration(html: string): number | undefined {
  const text = decodeTwitchHtml(html);
  const match = text.match(/"lengthSeconds"\s*:\s*(\d+)/);
  if (!match) return undefined;
  const duration = Number(match[1]);
  return Number.isFinite(duration) && duration > 0 ? duration : undefined;
}

export function parseTwitchPageAssets(html: string, href: string): TwitchPageAssets {
  const videoId = twitchPageVideoId(href);
  const text = decodeTwitchHtml(html);
  if (!videoId) {
    return { videoId: null, moments: [], captions: [] };
  }
  return {
    videoId,
    duration: parseTwitchDuration(text),
    seekPreviewsURL: pickSeekPreviewsUrl(collectTwitchStoryboardUrls(text, videoId), videoId),
    moments: parseTwitchMoments(text, videoId),
    captions: parseTwitchCaptionTracks(text, videoId)
  };
}
