import { sanitizeContentTitle } from '../content-title';

export function youtubeRecord(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function text(value: unknown, limit: number): string | undefined {
  return typeof value === 'string' ? value.slice(0, limit) : undefined;
}

function youtubeText(value: unknown): string | undefined {
  if (typeof value === 'string') return value;
  const record = youtubeRecord(value);
  if (typeof record?.simpleText === 'string') return record.simpleText;
  const first = Array.isArray(record?.runs) ? youtubeRecord(record.runs[0]) : null;
  return typeof first?.text === 'string' ? first.text : undefined;
}

export type NormalizedYoutubeCaption = {
  id: string;
  language: string;
  label: string;
  kind: 'captions' | 'subtitles';
  autoGenerated: boolean;
  baseUrl: string;
};

/** Host response fields are optional and may change independently of each other. */
export function readYoutubePlayerMetadata(raw: unknown): {
  videoId?: string;
  title?: string;
  duration?: number;
  description?: string;
  captionTracks: NormalizedYoutubeCaption[];
  storyboardSpec?: string;
} | null {
  const data = youtubeRecord(raw);
  if (!data) return null;
  const details = youtubeRecord(data.videoDetails);
  const renderer = youtubeRecord(youtubeRecord(data.captions)?.playerCaptionsTracklistRenderer);
  const tracks: unknown[] = Array.isArray(renderer?.captionTracks) ? renderer.captionTracks : [];
  const captionTracks = tracks.slice(0, 40).flatMap((value, index): NormalizedYoutubeCaption[] => {
    const track = youtubeRecord(value);
    if (!track || typeof track.baseUrl !== 'string' || !track.baseUrl || track.baseUrl.length > 32000) return [];
    const language = text(track.languageCode, 16) || '';
    const label = (youtubeText(track.name) || language).slice(0, 80);
    const autoGenerated = track.kind === 'asr';
    return [{
      id: `youtube:${text(track.vssId, 40) || language || index}`,
      language,
      label,
      kind: autoGenerated ? 'captions' : 'subtitles',
      autoGenerated,
      baseUrl: track.baseUrl
    }];
  });
  const rawDuration = details?.lengthSeconds;
  const duration = typeof rawDuration === 'number' || (typeof rawDuration === 'string' && rawDuration.trim())
    ? Number(rawDuration)
    : NaN;
  const microformat = youtubeRecord(youtubeRecord(data.microformat)?.playerMicroformatRenderer);
  const storyboard = youtubeRecord(youtubeRecord(data.storyboards)?.playerStoryboardSpecRenderer);
  return {
    videoId: text(details?.videoId, 20),
    title: sanitizeContentTitle(youtubeText(details?.title)) || sanitizeContentTitle(youtubeText(microformat?.title)) || undefined,
    duration: Number.isFinite(duration) && duration > 0 ? duration : undefined,
    description: text(details?.shortDescription, 20000),
    captionTracks,
    storyboardSpec: text(storyboard?.spec, 4000)
  };
}
