import { isAllowedMediaFetchUrl } from '../../platform/media-url-policy';
import { mediaProviderIntegrationEnabled } from '../../media-features/provider-flags';
import { isPatreonHost } from '../hosts';

export function patreonIntegrationEnabled(): boolean {
  return mediaProviderIntegrationEnabled('patreon');
}

function findMuxPlayer(): any | null {
  const start = document.querySelector('.theater-everywhere-video-active') || document.querySelector('video');
  let node: Node | null = start;
  while (node) {
    if (node instanceof Element && node.localName === 'mux-player') return node;
    node = node instanceof ShadowRoot ? node.host : node.parentNode;
  }
  return document.querySelector('mux-player');
}

function readPatreonPostText(): string {
  const nodes = document.querySelectorAll('article, [data-tag="post-content"], [data-tag="post-details"]');
  let best = '';
  for (const el of nodes) {
    const text = (el.textContent || '').replace(/\s+\n/g, '\n').trim();
    if (text.length > best.length) best = text;
  }
  return best.slice(0, 20000);
}

function decodeMuxPageText(html: string): string {
  return html
    .replace(/\\u002f/gi, '/')
    .replace(/\\u0026/gi, '&')
    .replace(/\\u003d/gi, '=')
    .replace(/\\\//g, '/');
}

function collectMuxPageAssets(html: string): Array<{
  playbackId: string;
  storyboardUrl?: string;
  captions: Array<{ id: string; url: string; language: string; label: string }>;
}> {
  const text = decodeMuxPageText(html);
  const byId = new Map<string, {
    playbackId: string;
    storyboardUrl?: string;
    captions: Array<{ id: string; url: string; language: string; label: string }>;
  }>();
  const ensure = (id: string) => {
    let asset = byId.get(id);
    if (!asset) {
      asset = { playbackId: id, captions: [] };
      byId.set(id, asset);
    }
    return asset;
  };
  for (const match of text.matchAll(
    /https:\/\/image\.mux\.com\/([A-Za-z0-9_-]+)\/storyboard\.(vtt|json)(\?[^"'\\\s<>]*)?/gi
  )) {
    const asset = ensure(match[1]);
    if (!asset.storyboardUrl || match[2].toLowerCase() === 'vtt') {
      asset.storyboardUrl = match[0].slice(0, 2000);
    }
  }
  for (const match of text.matchAll(
    /https:\/\/stream\.mux\.com\/([A-Za-z0-9_-]+)\/text\/([A-Za-z0-9_-]+)\.vtt(\?[^"'\\\s<>]*)?/gi
  )) {
    const asset = ensure(match[1]);
    const url = match[0].slice(0, 2000);
    if (asset.captions.some((caption) => caption.url === url)) continue;
    asset.captions.push({
      id: `patreon:${match[1]}:${match[2]}`.slice(0, 160),
      url,
      language: '',
      label: 'Captions'
    });
  }
  return [...byId.values()];
}

function pickMuxPageAsset(
  assets: ReturnType<typeof collectMuxPageAssets>,
  playbackId?: string
) {
  if (playbackId) {
    const match = assets.find((asset) => asset.playbackId === playbackId);
    if (match) return match;
  }
  return assets.find((asset) => asset.storyboardUrl || asset.captions.length > 0) || null;
}

function muxCaptionPath(url: string): string | null {
  try {
    const parsed = new URL(url);
    if (parsed.hostname.replace(/^www\./i, '').toLowerCase() !== 'stream.mux.com') return null;
    return /\/[^/]+\/text\/[^/]+\.vtt$/i.test(parsed.pathname) ? parsed.pathname.toLowerCase() : null;
  } catch {
    return null;
  }
}

function captionLooksAutoGenerated(label: string): boolean {
  return /auto[- ]generated|\(auto\)/i.test(label);
}

function readMuxTextTrackMeta(player: any): Array<{ language: string; label: string; autoGenerated: boolean }> {
  const meta: Array<{ language: string; label: string; autoGenerated: boolean }> = [];
  const lists = [player?.textTracks, player?.media?.textTracks, player?.media?.nativeEl?.textTracks];
  for (const list of lists) {
    if (!list) continue;
    const length = Number(list.length) || 0;
    for (let i = 0; i < length; i++) {
      const track = list[i];
      const kind = String(track?.kind || '');
      if (kind && kind !== 'subtitles' && kind !== 'captions') continue;
      const language = String(track?.language || '').slice(0, 16);
      const label = String(track?.label || '').slice(0, 80);
      if (!language && !label) continue;
      if (meta.some((item) => item.language === language && item.label === label)) continue;
      meta.push({
        language,
        label,
        autoGenerated: captionLooksAutoGenerated(label)
      });
    }
  }
  return meta;
}

function readMuxHlsCaptionTracks(player: any): Array<{
  id: string;
  language: string;
  label: string;
  kind: 'captions' | 'subtitles';
  url: string;
  autoGenerated?: boolean;
}> {
  const hls = player?._hls || player?.media?._hls || player?.media?.nativeEl?._hls;
  const list = Array.isArray(hls?.subtitleTracks) ? hls.subtitleTracks : [];
  const tracks: Array<{
    id: string;
    language: string;
    label: string;
    kind: 'captions' | 'subtitles';
    url: string;
    autoGenerated?: boolean;
  }> = [];
  for (const track of list.slice(0, 12)) {
    const url = typeof track?.url === 'string' ? track.url.slice(0, 2000) : '';
    if (!isAllowedMediaFetchUrl({ provider: 'patreon', kind: 'caption-track', url }, window.location.href)) continue;
    const label = String(track.name || track.label || track.lang || 'Captions').slice(0, 80);
    tracks.push({
      id: `patreon-hls:${String(track.id ?? url).slice(0, 80)}`,
      language: String(track.lang || track.language || '').slice(0, 16),
      label,
      kind: 'subtitles',
      url,
      autoGenerated: captionLooksAutoGenerated(label)
    });
  }
  return tracks;
}

export function readPatreonSnapshot(): Record<string, unknown> | null {
  try {
    if (!isPatreonHost()) return null;
    const player = findMuxPlayer();
    const playbackIdRaw = player?.playbackId || player?.getAttribute?.('playback-id');
    const playbackId = playbackIdRaw != null ? String(playbackIdRaw).split('?')[0].slice(0, 80) : '';
    const page = pickMuxPageAsset(
      collectMuxPageAssets(document.documentElement?.innerHTML || ''),
      playbackId
    );
    const storyboard = typeof player?.storyboard === 'string' ? player.storyboard
      : typeof player?.storyboardSrc === 'string' ? player.storyboardSrc
      : player?.getAttribute?.('storyboard-src');
    const token = player?.tokens?.storyboard || player?.getAttribute?.('storyboard-token');
    let storyboardUrl = typeof storyboard === 'string' ? storyboard.slice(0, 2000) : '';
    if (!storyboardUrl) storyboardUrl = page?.storyboardUrl || '';
    if (!storyboardUrl && playbackId && /^[A-Za-z0-9_-]+$/.test(playbackId) && token) {
      const url = new URL(`https://image.mux.com/${playbackId}/storyboard.vtt`);
      url.searchParams.set('format', 'webp');
      url.searchParams.set('token', String(token));
      storyboardUrl = url.toString().slice(0, 2000);
    }
    const chapters = Array.isArray(player?.chapters)
      ? player.chapters.slice(0, 80).map((chapter: any) => ({
          startTime: Number(chapter?.startTime ?? chapter?.start),
          title: String(chapter?.value || chapter?.title || '').slice(0, 120)
        })).filter((chapter: { startTime: number; title: string }) => Number.isFinite(chapter.startTime) && chapter.title)
      : [];
    const hlsCaptions = player ? readMuxHlsCaptionTracks(player) : [];
    const captionTracks = [...hlsCaptions];
    for (const caption of page?.captions || []) {
      const path = muxCaptionPath(caption.url);
      if (captionTracks.some((track) => track.url === caption.url || muxCaptionPath(track.url) === path)) continue;
      captionTracks.push({
        id: caption.id,
        language: caption.language,
        label: caption.label,
        kind: captionLooksAutoGenerated(caption.label) ? 'captions' : 'subtitles',
        url: caption.url,
        autoGenerated: captionLooksAutoGenerated(caption.label)
      });
    }
    const textMeta = player ? readMuxTextTrackMeta(player) : [];
    if (captionTracks.length === 1 && textMeta.length > 0) {
      const meta = textMeta[0];
      if (!captionTracks[0].language && meta.language) captionTracks[0].language = meta.language;
      if ((captionTracks[0].label === 'Captions' || !captionTracks[0].label) && meta.label) {
        captionTracks[0].label = meta.label;
      }
      captionTracks[0].autoGenerated = Boolean(
        captionTracks[0].autoGenerated || meta.autoGenerated || captionLooksAutoGenerated(captionTracks[0].label)
      );
    }
    const description = readPatreonPostText();
    if (!storyboardUrl && chapters.length === 0 && captionTracks.length === 0 && !description) return null;
    return {
      playbackId: playbackId || page?.playbackId || undefined,
      duration: Number(player?.duration) || undefined,
      storyboardUrl: storyboardUrl || undefined,
      description: description || undefined,
      chapters,
      captionTracks
    };
  } catch {
    return null;
  }
}
